import { damageTypes, targets } from '../cooldowns/constants';

export const dsrp5Info =
{
    name: "Dragonsong's Reprise (Ultimate) | Intermission & Phase 5",
    abbreviation: "DSR/DRU P5",
    boss: "Ser Charibert, Haurchefaunt's mortality, & King Thordan",
    length: 247,
    level: 90
}

export const dsrp5Skills =
{
    planar_prison: {
        id: "planar_prison",
        name: "Planar Prison",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Party pulled into small circle with Charibert",
    },
    spear_of_the_fury: {
        id: "spear_of_the_fury",
        name: "Spear of the Fury",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Shockwaves begin",
    },
    pure_of_heart: {
        id: "pure_of_heart",
        name: "Pure of Heart",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Charibert must be under ~30% HP or you die",
    },
    shockwave: {
        id: "shockwave",
        name: "Shockwave",
        damageType: damageTypes.DARK,
        target: targets.PARTY,
        avoidable: false,
        notes: "Ongoing pulse damage on party & Haurchefaunt until spear dies",
    },
    brightwing: {
        id: "brightwing",
        name: "Brightwing",
        damageType: damageTypes.MAGIC,
        target: targets.PROXIMITY_CLOSE2,
        avoidable: false,
        notes: "Closest two party members targeted with cleaves",
    },
    skyblind: {
        id: "skyblind",
        name: "Skyblind",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "AoEs dropped upon expiration of Skyblind debuff explode",
    },
    pierce: {
        id: "pierce",
        name: "Pierce",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Kill spear before Haurchefaunt dies",
    },
    incarnation: {
        id: "incarnation",
        name: "Incarnation",
        damageType: damageTypes.NONE,
        target: targets.NONE,
        avoidable: false,
        notes: "Thordan takes control of Vidofnir, Vedrfolnir, and Darkscale",
    },
    the_dragons_eye: {
        id: "the_dragons_eye",
        name: "The Dragon's Eye",
        damageType: damageTypes.NONE,
        target: targets.NONE,
        avoidable: false,
        notes: "Buff on Thordan makes attacks hurt more than phase 2",
    },
    wrath_of_the_heavens: {
        id: "wrath_of_the_heavens",
        name: "Wrath of the Heavens",
        damageType: damageTypes.NONE,
        target: targets.NONE,
        avoidable: false,
    },
    twisting_dive: {
        id: "twisting_dive",
        name: "Twisting Dive",
        damageType: damageTypes.PHYS,
        target: targets.PARTY,
        avoidable: true,
        notes: "Divebomb + twisters spawn under each party member",
    },
    chain_lightning: {
        id: "chain_lightning",
        name: "Chain Lightning",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Two party members afflicted with Thunderstruck, will be hit with Lightning Storm AoE upon expiration",
    },
    spiral_pierce: {
        id: "spiral_pierce",
        name: "Spiral Pierce",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Two party members get tethered to two knights for proximity-based damage and receive a 12s Magic Vuln Up",
    },
    skyward_leap: {
        id: "skyward_leap",
        name: "Skyward Leap",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "One party member gets a blue marker for a large AoE and receive a 12s Magic Vuln Up and 3s Phys Vuln Up",
    },
    ascalons_mercy_revealed: {
        id: "ascalons_mercy_revealed",
        name: "Ascalon's Mercy Revealed",
        damageType: damageTypes.PHYS,
        target: targets.PARTY,
        avoidable: false,
        notes: "Unavoidable proteans on entire party",
    },
    altar_flare: {
        id: "altar_flare",
        name: "Altar Flare",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Four eruptions spawn under random party member",
    },
    liquid_heaven: {
        id: "liquid_heaven",
        name: "Liquid Heaven",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: false,
        notes: "Random party member targeted for five AoEs which drop persisting lethal puddles",
    },
    cauterize: {
        id: "cauterize",
        name: "Cauterize",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Divebombs from Darkscale & Vidofnir",
    },
    empty_dimension: {
        id: "empty_dimension",
        name: "Empty Dimension",
        damageType: damageTypes.MAGIC,
        target: targets.DIRECTIONAL,
        avoidable: true,
        notes: "Donut AoE on Grinnaux",
    },
    heavenly_heel: {
        id: "heavenly_heel",
        name: "Heavenly Heel",
        damageType: damageTypes.PHYS,
        target: targets.MT,
        avoidable: false,
        notes: "Tankbuster; applies Slashing Resistance Down",
    },
    ancient_quaga: {
        id: "ancient_quaga",
        name: "Ancient Quaga",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
    },
    ascalons_might: {
        id: "ascalons_might",
        name: "Ascalon's Might",
        damageType: damageTypes.PHYS,
        target: targets.MT,
        avoidable: false,
        notes: "3-hit cone tankbuster",
    },
    death_of_the_heavens: {
        id: "death_of_the_heavens",
        name: "Death of the Heavens",
        damageType: damageTypes.NONE,
        target: targets.NONE,
        avoidable: false,
    },
    deathstorm: {
        id: "deathstorm",
        name: "Deathstorm",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Applies Doom to four party members",
    },
    heavy_impact: {
        id: "heavy_impact",
        name: "Heavy Impact",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Expanding concentric earthquake AoE",
    },
    wings_of_salvation: {
        id: "wings_of_salvation",
        name: "Wings of Salvation",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Light puddles dropped under players without Doom; used to cleanse Doom",
    },
    lightning_storm: {
        id: "lightning_storm",
        name: "Lightning Storm",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "AoEs on all party members",
    },
    spear_of_the_fury_2: {
        id: "spear_of_the_fury_2",
        name: "Spear of the Fury",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Line AoEs from a knight from the edge of the arena",
    },
    the_dragons_gaze_glory: {
        id: "the_dragons_gaze_glory",
        name: "The Dragon's Gaze/Glory",
        damageType: damageTypes.NONE,
        target: targets.GAZE,
        avoidable: true,
        notes: "Applies Hysteria if looking at eyeball or Thordan",
    },
    faith_unmoving: {
        id: "faith_unmoving",
        name: "Faith Unmoving",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: false,
        notes: "Knockback from Grinnaux",
    },
    heavensflame: {
        id: "heavensflame",
        name: "Heavensflame",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Playstation chains spawn, followed by AoEs on all party members"
    },
    holy_meteors: {
        id: "holy_meteors",
        name: "Holy Meteors",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Targetable meteor adds spawn",
    },
    aetheric_burst: {
        id: "aetheric_burst",
        name: "Aetheric Burst",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
    },
}

export const dsrp5Timeline =
[
    {
        ...dsrp5Skills["spear_of_the_fury"],
        startTime: 1,
        endTime: 11,
    },
    {
        ...dsrp5Skills["planar_prison"],
        startTime: 1,
        endTime: 1,
    },
    {
        ...dsrp5Skills["pure_of_heart"],
        startTime: 1,
        endTime: 36,
    },
    {
        ...dsrp5Skills["shockwave"],
        startTime: 11,
        endTime: 51,
    },
    {
        ...dsrp5Skills["brightwing"],
        startTime: 14,
        endTime: 15,
    },
    {
        ...dsrp5Skills["brightwing"],
        startTime: 18,
        endTime: 19,
    },
    {
        ...dsrp5Skills["brightwing"],
        startTime: 22,
        endTime: 23,
    },
    {
        ...dsrp5Skills["brightwing"],
        startTime: 26,
        endTime: 27,
    },
    {
        ...dsrp5Skills["skyblind"],
        startTime: 21,
        endTime: 22,
    },
    {
        ...dsrp5Skills["skyblind"],
        startTime: 25,
        endTime: 26,
    },
    {
        ...dsrp5Skills["skyblind"],
        startTime: 29,
        endTime: 30,
    },
    {
        ...dsrp5Skills["skyblind"],
        startTime: 33,
        endTime: 34,
    },
    {
        ...dsrp5Skills["pierce"],
        startTime: 40,
        endTime: 51,
    },
    {
        ...dsrp5Skills["incarnation"],
        startTime: 66,
        endTime: 70,
    },
    {
        ...dsrp5Skills["the_dragons_eye"],
        startTime: 73,
        endTime: 76,
    },
    {
        ...dsrp5Skills["wrath_of_the_heavens"],
        startTime: 91,
        endTime: 95,
    },
    {
        ...dsrp5Skills["twisting_dive"],
        startTime: 99,
        endTime: 105,
    },
    {
        ...dsrp5Skills["chain_lightning"],
        startTime: 102,
        endTime: 103,
    },
    {
        ...dsrp5Skills["skyward_leap"],
        startTime: 104,
        endTime: 105,
    },
    {
        ...dsrp5Skills["spiral_pierce"],
        startTime: 104,
        endTime: 105,
    },
    {
        ...dsrp5Skills["ascalons_mercy_revealed"],
        startTime: 108,
        endTime: 111,
    },
    {
        ...dsrp5Skills["altar_flare"],
        startTime: 111,
        endTime: 119,
    },
    {
        ...dsrp5Skills["liquid_heaven"],
        startTime: 111,
        endTime: 117,
    },
    {
        ...dsrp5Skills["cauterize"],
        startTime: 112,
        endTime: 116,
    },
    {
        ...dsrp5Skills["empty_dimension"],
        startTime: 113,
        endTime: 118,
    },
    {
        ...dsrp5Skills["lightning_storm"],
        startTime: 117,
        endTime: 118,
    },
    {
        ...dsrp5Skills["ancient_quaga"],
        startTime: 119,
        endTime: 125,
    },
    {
        ...dsrp5Skills["heavenly_heel"],
        startTime: 129,
        endTime: 133,
    },
    {
        ...dsrp5Skills["ascalons_might"],
        startTime: 136,
        endTime: 140,
    },
    {
        ...dsrp5Skills["death_of_the_heavens"],
        startTime: 147,
        endTime: 151,
    },
    {
        ...dsrp5Skills["deathstorm"],
        startTime: 157,
        endTime: 158,
    },
    {
        ...dsrp5Skills["heavy_impact"],
        startTime: 159,
        endTime: 171,
    },
    {
        ...dsrp5Skills["spear_of_the_fury_2"],
        startTime: 161,
        endTime: 167,
    },
    {
        ...dsrp5Skills["lightning_storm"],
        startTime: 161,
        endTime: 167,
    },
    {
        ...dsrp5Skills["twisting_dive"],
        startTime: 161,
        endTime: 167,
    },
    {
        ...dsrp5Skills["cauterize"],
        startTime: 161,
        endTime: 167,
    },
    {
        ...dsrp5Skills["wings_of_salvation"],
        startTime: 167,
        endTime: 177,
    },
    {
        ...dsrp5Skills["heavensflame"],
        startTime: 175,
        endTime: 182,
    },
    {
        ...dsrp5Skills["the_dragons_gaze_glory"],
        startTime: 175,
        endTime: 185,
    },
    {
        ...dsrp5Skills["faith_unmoving"],
        startTime: 176,
        endTime: 185,
    },
    {
        ...dsrp5Skills["holy_meteors"],
        startTime: 190,
        endTime: 205,
    },
    {
        ...dsrp5Skills["ancient_quaga"],
        startTime: 213,
        endTime: 219,
    },
    {
        ...dsrp5Skills["heavenly_heel"],
        startTime: 225,
        endTime: 229,
    },
    {
        ...dsrp5Skills["ascalons_might"],
        startTime: 232,
        endTime: 236,
    },
    {
        ...dsrp5Skills["aetheric_burst"],
        startTime: 241,
        endTime: 247,
    },
]