import { damageTypes, targets } from '../cooldowns/constants';

export const dsrpostdoorbossInfo =
{
    name: "Dragonsong's Reprise (Ultimate) | Phases 2-7",
    abbreviation: "DSR/DRU P2-P7",
    boss: "basically the entire cast of Heavensward",
    length: 1136,
    level: 90
}

export const dsrpostdoorbossSkills =
{
    aetheric_burst: {
        id: "aetheric_burst",
        name: "Aetheric Burst",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
    },
    akh_afah: {
        id: "akh_afah",
        name: "Akh Afah",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Stacks targeting each healer; Nidhogg & Hraesvelgr must be within 3% HP of each other or they do lethal damage",
    },
    akh_morn: {
        id: "akh_morn",
        name: "Akh Morn",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Four hits of stack damage on a random player that leave persisting puddles which inflict a heavy bleed",
    },
    akh_morns_edge_5: {
        id: "akh_morns_edge_5",
        name: "Akh Morn's Edge (5 hits)",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: false,
        notes: "Three towers spawn (two require three people one requires both tanks) hit players in them five times",
    },
    akh_morns_edge_6: {
        id: "akh_morns_edge_6",
        name: "Akh Morn's Edge (6 hits)",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: false,
        notes: "Three towers spawn (two require three people one requires both tanks) hit players in them six times",
    },
    akh_morns_edge_7: {
        id: "akh_morns_edge_7",
        name: "Akh Morn's Edge (7 hits)",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: false,
        notes: "Three towers spawn (two require three people one requires both tanks) hit players in them seven times",
    },
    altar_flare: {
        id: "altar_flare",
        name: "Altar Flare",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Four eruptions spawn under random party member",
    },
    alternative_end: {
        id: "alternative_end",
        name: "Alternative End",
        damageType: damageTypes.MAGIC,
        target: targets.PARRTY,
        avoidable: false,
    },
    ancient_quaga: {
        id: "ancient_quaga",
        name: "Ancient Quaga",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
    },
    ascalons_mercy: {
        id: "ascalons_mercy",
        name: "Ascalon's Mercy Concealed",
        damageType: damageTypes.PHYS,
        target: targets.PARTY,
        avoidable: true,
        notes: "Non-telegraphed baited proteans",
    },
    ascalons_mercy_revealed: {
        id: "ascalons_mercy_revealed",
        name: "Ascalon's Mercy Revealed",
        damageType: damageTypes.PHYS,
        target: targets.PARTY,
        avoidable: false,
        notes: "Unavoidable proteans on entire party",
    },
    ascalons_might: {
        id: "ascalons_might",
        name: "Ascalon's Might",
        damageType: damageTypes.PHYS,
        target: targets.MT,
        avoidable: false,
        tankbuster: true,
        notes: "3-hit cone tankbuster",
    },
    brightwing: {
        id: "brightwing",
        name: "Brightwing",
        damageType: damageTypes.MAGIC,
        target: targets.PROXIMITY_CLOSE2,
        avoidable: false,
        notes: "Closest two party members targeted with cleaves",
    },
    broad_swing: {
        id: "broad_swing",
        name: "Broad Swing",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: true,
        notes: "Thordan cleaves 120 degrees to his left/right/rear",
    },
    cauterize_1: {
        id: "cauterize_1",
        name: "Cauterize",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Divebombs from Darkscale & Vidofnir",
    },
    cauterize: {
        id: "cauterize",
        name: "Cauterize",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Divebomb",
    },
    chain_lightning: {
        id: "chain_lightning",
        name: "Chain Lightning",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Two party members afflicted with Thunderstruck, will be hit with Lightning Storm AoE upon expiration",
    },
    conviction: {
        id: "conviction",
        name: "Conviction",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Towers",
    },
    dark_jump_1: {
        id: "dark_jump_1",
        name: "Dark Jump 1",
        damageType: damageTypes.PHYS,
        target: targets.PARTY,
        avoidable: false,
        notes: "Party members marked First In Line jumped on; towers spawn relative to them based on high jump/elusive jump/spineshatter dive debuffs",
    },
    dark_jump_2: {
        id: "dark_jump_2",
        name: "Dark Jump 2",
        damageType: damageTypes.PHYS,
        target: targets.PARTY,
        avoidable: false,
        notes: "Party members marked Second In Line jumped on; towers spawn relative to them based on high jump/elusive jump/spineshatter dive debuffs",
    },
    dark_jump_3: {
        id: "dark_jump_3",
        name: "Dark Jump 3",
        damageType: damageTypes.PHYS,
        target: targets.PARTY,
        avoidable: false,
        notes: "Party members marked Third In Line jumped on; towers spawn relative to them based on high jump/elusive jump/spineshatter dive debuffs",
    },
    dark_staggering_breath: {
        id: "dark_staggering_breath",
        name: "Dark/Staggering Breath",
        damageType: damageTypes.PHYS,
        target: targets.MT,
        avoidable: false,
        tankbuster: true,
        notes: "If Nidhogg's mouth is not glowing Nidhogg tank takes Staggering Breath a solo buster; if both dragon mouths are glowing Nidhogg tank takes Dark Breath which applies the Dark Orb debuff cancelled by stacking with Hraesvelgr tank taking Holy Breath.",
    },
    darkdragon_dive: {
        id: "darkdragon_dive",
        name: "Darkdragon Dive",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: false,
        notes: "Towers",
    },
    death_of_the_heavens: {
        id: "death_of_the_heavens",
        name: "Death of the Heavens",
        damageType: damageTypes.NONE,
        target: targets.NONE,
        avoidable: false,
    },
    deathstorm: {
        id: "deathstorm",
        name: "Deathstorm",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Applies Doom to four party members",
    },
    dimensional_collapse: {
        id: "dimensional_collapse",
        name: "Dimensional Collapse",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: true,
        notes: "Expanding AoEs",
    },
    dive_from_grace: {
        id: "dive_from_grace",
        name: "Dive From Grace",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Applies jump debuffs to party",
    },
    drachenlance: {
        id: "drachenlance",
        name: "Drachenlance",
        damageType: damageTypes.PHYS,
        target: targets.PARTY,
        avoidable: true,
        notes: "90 degree cleave targeted at random player",
    },
    dread_wyrmsbreath: {
        id: "dread_wyrmsbreath",
        name: "Dread Wyrmsbreath",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Three non-tanks tethered to Nidhogg for cone AoE with proximity-based damage that applies Pyretic and Boiling. Getting hit by cone from Hraesvelgr cancels Boiling.",
    },
    empty_dimension: {
        id: "empty_dimension",
        name: "Empty Dimension",
        damageType: damageTypes.MAGIC,
        target: targets.DIRECTIONAL,
        avoidable: true,
        notes: "Donut AoE on Grinnaux",
    },
    exaflares_edge: {
        id: "exaflares_edge",
        name: "Exaflare's Edge",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Three tri-directional exaflares spawn",
    },
    eye_of_the_tyrant: {
        id: "eye_of_the_tyrant",
        name: "Eye of the Tyrant",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Stack on a random party member",
    },
    faith_unmoving: {
        id: "faith_unmoving",
        name: "Faith Unmoving",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: false,
        notes: "Knockback from Grinnaux",
    },
    final_chorus: {
        id: "final_chorus",
        name: "Final Chorus",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Opening raidwide",
    },
    fire_debuffs_expire: {
        id: "fire_debuffs_expire",
        name: "Spreading Flame & Entangled Pyre Expire",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
    },
    flames_ice_of_ascalon: {
        id: "flames_ice_of_ascalon",
        name: "Flames/Ice of Ascalon",
        damageType: damageTypes.MAGIC,
        target: targets.DIRECTIONAL,
        avoidable: true,
        notes: "Chariot (fire) or donut (ice) around Thordan",
    },
    flare_nova_star: {
        id: "flare_nova_star",
        name: "Flare Nova/Star",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Magic damage to party members as they pop orbs",
    },
    geirskogul: {
        id: "geirskogul",
        name: "Geirskogul",
        damageType: damageTypes.MAGIC,
        target: targets.PROXIMITY_NEAR,
        avoidable: true,
        notes: "Line AoE targeted at closest player to each clone",
    },
    gigaflares_edge: {
        id: "gigaflares_edge",
        name: "Gigaflare's Edge",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: false,
        notes: "Three proximity-based AoEs spawn around arena",
    },
    gnash_lash: {
        id: "gnash_lash",
        name: "Lash/Gnash",
        damageType: damageTypes.MAGIC,
        target: targets.DIRECTIONAL,
        avoidable: true,
        notes: "Lash (in) or Gnash (out)",
    },
    gnash_lash_cast: {
        id: "gnash_lash_cast",
        name: "Lash and Gnash/Gnash and Lash",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Skill name indicates order of Lash (in)/Gnash (out)",
    },
    great_wyrmsbreath: {
        id: "great_wyrmsbreath",
        name: "Great Wyrmsbreath",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Three non-tanks tethered to Hraesvelgr for cone AoE with proximity-based damage that applies Deep Freeze and Freezing. Getting hit by cone fron Nidhogg cancels Freezing.",
    },
    hallowed_plume: {
        id: "hallowed_plume",
        name: "Hallowed Plume",
        damageType: damageTypes.MAGIC,
        target: targets.MT + " + " + targets.OT,
        avoidable: false,
        tankbuster: true,
        notes: "AoE tankbusters targeting closest two players if Hraesvelgr's head is down or furthest two players if his head is up",
    },
    hallowed_wings: {
        id: "hallowed_wings",
        name: "Hallowed Wings",
        damageType: damageTypes.MAGIC,
        target: targets.DIRECTIONAL,
        avoidable: true,
        notes: "Hraesvelgr cleaves half of the arena based on which wing is glowing",
    },
    hatebound: {
        id: "hatebound",
        name: "Hatebound",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Four party members get red debuff, four party members get blue debuff",
    },
    heavenly_heel: {
        id: "heavenly_heel",
        name: "Heavenly Heel",
        damageType: damageTypes.PHYS,
        target: targets.MT,
        avoidable: false,
        tankbuster: true,
        notes: "Tankbuster; applies Slashing Resistance Down",
    },
    heavensflame: {
        id: "heavensflame",
        name: "Heavensflame",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Playstation chains spawn, followed by AoEs on all players",
    },
    heavy_impact: {
        id: "heavy_impact",
        name: "Heavy Impact",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Expanding concentric earthquake AoE",
    },
    hiemal_storm: {
        id: "hiemal_storm",
        name: "Hiemal Storm",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "DPS or T/H targeted with shared ice AoEs",
    },
    holy_bladedance: {
        id: "holy_bladedance",
        name: "Holy Bladedance",
        damageType: damageTypes.PHYS,
        target: targets.MT + " + " + targets.OT,
        avoidable: false,
        tankbuster: true,
        notes: "Multi-hit tankbuster on downed tank",
    },
    holy_comet_cast: {
        id: "holy_comet_cast",
        name: "Holy Comet",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Two players marked for 7 comets",
    },
    holy_comet_fall: {
        id: "holy_comet_fall",
        name: "Comet Falls",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: false,
        notes: "Small proximity damage from comet",
    },
    holy_meteors: {
        id: "holy_meteors",
        name: "Holy Meteors",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Targetable meteor adds spawn",
    },
    holy_shield_bash: {
        id: "holy_shield_bash",
        name: "Holy Shield Bash",
        damageType: damageTypes.PHYS,
        target: targets.MT + " + " + targets.OT,
        avoidable: false,
        tankbuster: true,
        notes: "Tether tankbuster; target is Down for the Count",
    },
    holy_staggering_breath: {
        id: "holy_staggering_breath",
        name: "Holy/Staggering Breath",
        damageType: damageTypes.PHYS,
        target: targets.MT,
        avoidable: false,
        tankbuster: true,
        notes: "If Hraesvelgr's mouth is not glowing Hraesvelgr tank takes Staggering Breath a solo buster; if both dragon mouths are glowing Hraesvelgr tank takes Holy Breath which applies Holy Orb debuff cancelled by stacking with Nidhogg tank taking Dark Breath.",
    },
    hot_tail_wing: {
        id: "hot_tail_wing",
        name: "Hot Tail/Wing",
        damageType: damageTypes.MAGIC,
        target: targets.DIRECTIONAL,
        avoidable: true,
        notes: "Line cleave through Nidhogg's center (Tail) or outside his hitbox from his wings (Wing)",
    },
    incarnation: {
        id: "incarnation",
        name: "Incarnation",
        damageType: damageTypes.NONE,
        target: targets.NONE,
        avoidable: false,
        notes: "Thordan takes control of Vidofnir, Vedrfolnir, and Darkscale",
    },
    lightning_storm: {
        id: "lightning_storm",
        name: "Lightning Storm",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "AoEs on all party members",
    },
    liquid_heaven: {
        id: "liquid_heaven",
        name: "Liquid Heaven",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: false,
        notes: "Random party member targeted for five AoEs which drop persisting lethal puddles",
    },
    mirage_dive: {
        id: "mirage_dive",
        name: "Mirage Dive",
        damageType: damageTypes.PHYS,
        target: targets.PARTY,
        avoidable: false,
        notes: "Dive on two players with red tether; applies Piercing Resistance Down",
    },
    morn_afahs_edge: {
        id: "morn_afahs_edge",
        name: "Morn Afah's Edge",
        damageType: damageTypes.ENRAGE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Enrage sequence; towers spawn in sets of three killing players who take them until all players are dead",
    },
    mortal_vow: {
        id: "mortal_vow",
        name: "Mortal Vow",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Random party member receives initial Mortal Vow debuff",
    },
    mortal_vow_expires: {
        id: "mortal_vow_expires",
        name: "Mortal Vow Expires",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Mortal Vow expires damaging the player who had it and applying it to one player in the area around them",
    },
    pierce: {
        id: "pierce",
        name: "Pierce",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Kill spear before Haurchefaunt dies",
    },
    planar_prison: {
        id: "planar_prison",
        name: "Planar Prison",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Party pulled into small circle with Charibert",
    },
    pure_of_heart: {
        id: "pure_of_heart",
        name: "Pure of Heart",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Charibert must be under ~30% HP or you die",
    },
    resentment: {
        id: "resentment",
        name: "Resentment",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Raidwide + bleed",
    },
    revenge_of_the_horde: {
        id: "revenge_of_the_horde",
        name: "Revenge of the Horde",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
    },
    sacred_sever: {
        id: "sacred_sever",
        name: "Sacred Sever",
        damageType: damageTypes.PHYS,
        target: targets.PARTY,
        avoidable: false,
        notes: "DRK plunges on players marked 1 & 2; proximity-based stack damage",
    },
    sanctity_of_the_ward: {
        id: "sanctity_of_the_ward",
        name: "Sanctity of the Ward",
        damageType: damageTypes.NONE,
        target: targets.NONE,
        avoidable: false,
    },
    shining_blade: {
        id: "shining_blade",
        name: "Shining Blade",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "PLDs dash around arena leaving exploding orbs behind",
    },
    shockwave_1: {
        id: "shockwave_1",
        name: "Shockwave",
        damageType: damageTypes.DARK,
        target: targets.PARTY,
        avoidable: false,
        notes: "Ongoing pulse damage on party & Haurchefaunt until spear dies",
    },
    shockwave: {
        id: "shockwave",
        name: "Shockwave",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
    },
    skyblind: {
        id: "skyblind",
        name: "Skyblind",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "AoEs dropped upon expiration of Skyblind debuff explode",
    },
    skyward_leap: {
        id: "skyward_leap",
        name: "Skyward Leap",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Large AoEs on 3 marked players",
    },
    skyward_leap_1: {
        id: "skyward_leap_1",
        name: "Skyward Leap",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "One party member gets a blue marker for a large AoE and receive a 12s Magic Vuln Up and 3s Phys Vuln Up",
    },
    soul_of_devotion_friendship: {
        id: "soul_of_devotion_friendship",
        name: "Soul of Devotion/Friendship",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Red & blue buffs go out, get both",
    },
    soul_tether: {
        id: "soul_tether",
        name: "Soul Tether",
        damageType: damageTypes.MAGIC,
        target: targets.MT + " + " + targets.OT,
        avoidable: false,
        tankbuster: true,
        notes: "Heavy-hitting tankbuster tethers",
    },
    spear_of_the_fury: {
        id: "spear_of_the_fury",
        name: "Spear of the Fury",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Shockwaves begin",
    },
    spear_of_the_fury_2: {
        id: "spear_of_the_fury_2",
        name: "Spear of the Fury",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Line AoEs from a knight from the edge of the arena",
    },
    spiral_pierce: {
        id: "spiral_pierce",
        name: "Spiral Pierce",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Two party members get tethered to two knights for proximity-based damage and receive a 12s Magic Vuln Up",
    },
    spiral_thrust: {
        id: "spiral_thrust",
        name: "Spiral Thrust",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: true,
        notes: "3 dives across the arena; leaves one cardinal/intercardinal pair safe",
    },
    steep_in_rage: {
        id: "steep_in_rage",
        name: "Steep in Rage",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTy,
        avoidable: false,
    },
    strength_of_the_ward: {
        id: "strength_of_the_ward",
        name: "Strength of the Ward",
        damageType: damageTypes.NONE,
        target: targets.NONE,
        avoidable: false,
    },
    the_dragons_eye: {
        id: "the_dragons_eye",
        name: "The Dragon's Eye",
        damageType: damageTypes.NONE,
        target: targets.NONE,
        avoidable: false,
        notes: "Buff on Thordan makes attacks hurt more than phase 2",
    },
    the_dragons_gaze_glory: {
        id: "the_dragons_gaze_glory",
        name: "The Dragon's Gaze/Glory",
        damageType: damageTypes.NONE,
        target: targets.GAZE,
        avoidable: true,
        notes: "Applies Hysteria if looking at eyeball or Thordan",
    },
    the_dragons_rage: {
        id: "the_dragons_rage",
        name: "The Dragon's Rage",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Stack damage on unmarked players",
    },
    touchdown: {
        id: "touchdown",
        name: "Touchdown",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: false,
        notes: "Proximity damage from where dragon lands",
    },
    trinity_other: {
        id: "trinity_other",
        name: "Trinity (DPS/Healer)",
        damageType: damageTypes.PHYS,
        target: targets.PROXIMITY_NEAR,
        avoidable: false,
        notes: "Physical auto on closest player not 1st or 2nd in aggro",
    },
    trinity_tank: {
        id: "trinity_tank",
        name: "Trinity (Tanks)",
        damageType: damageTypes.MAGIC,
        target: targets.AGGRO_1_2,
        avoidable: false,
        notes: "Dark-aspected auto hits 1st in aggro, light-aspected auto hits 2nd in aggro",
    },
    twisting_dive: {
        id: "twisting_dive",
        name: "Twisting Dive",
        damageType: damageTypes.PHYS,
        target: targets.PARTY,
        avoidable: true,
        notes: "Divebomb + twisters spawn under each party member",
    },
    ultimate_end: {
        id: "ultimate_end",
        name: "Ultimate End",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Heavy-hitting raidwide (no cast)",
    },
    wings_of_salvation: {
        id: "wings_of_salvation",
        name: "Wings of Salvation",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Light puddles dropped under players without Doom; used to cleanse Doom",
    },
    wrath_of_the_heavens: {
        id: "wrath_of_the_heavens",
        name: "Wrath of the Heavens",
        damageType: damageTypes.NONE,
        target: targets.NONE,
        avoidable: false,
    },
    wroth_flames: {
        id: "wroth_flames",
        name: "Wroth Flames",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Applies Spreading Flame debuff to four random players and Entangled Pyre debuff to two random players",
    },
}

export const dsrpostdoorbossTimeline =
[
    {
        ...dsrpostdoorbossSkills["ascalons_mercy"],
        startTime: 12,
        endTime: 13,
    },
    {
        ...dsrpostdoorbossSkills["ascalons_might"],
        startTime: 15,
        endTime: 18,
    },
    {
        ...dsrpostdoorbossSkills["strength_of_the_ward"],
        startTime: 25,
        endTime: 29,
    },
    {
        ...dsrpostdoorbossSkills["spiral_thrust"],
        startTime: 36,
        endTime: 42,
    },
    {
        ...dsrpostdoorbossSkills["heavy_impact"],
        startTime: 36,
        endTime: 46,
    },
    {
        ...dsrpostdoorbossSkills["lightning_storm"],
        startTime: 41,
        endTime: 42,
    },
    {
        ...dsrpostdoorbossSkills["ascalons_mercy"],
        startTime: 47,
        endTime: 49,
    },
    {
        ...dsrpostdoorbossSkills["dimensional_collapse"],
        startTime: 49,
        endTime: 58,
    },
    {
        ...dsrpostdoorbossSkills["the_dragons_rage"],
        startTime: 52,
        endTime: 57,
    },
    {
        ...dsrpostdoorbossSkills["skyward_leap"],
        startTime: 57,
        endTime: 58,
    },
    {
        ...dsrpostdoorbossSkills["holy_shield_bash"],
        startTime: 57,
        endTime: 58,
    },
    {
        ...dsrpostdoorbossSkills["holy_bladedance"],
        startTime: 61,
        endTime: 63,
    },
    {
        ...dsrpostdoorbossSkills["conviction"],
        startTime: 63,
        endTime: 64,
    },
    {
        ...dsrpostdoorbossSkills["ancient_quaga"],
        startTime: 64,
        endTime: 70,
    },
    {
        ...dsrpostdoorbossSkills["heavenly_heel"],
        startTime: 76,
        endTime: 80,
    },
    {
        ...dsrpostdoorbossSkills["ascalons_might"],
        startTime: 83,
        endTime: 86,
    },
    {
        ...dsrpostdoorbossSkills["sanctity_of_the_ward"],
        startTime: 93,
        endTime: 97,
    },
    {
        ...dsrpostdoorbossSkills["the_dragons_gaze_glory"],
        startTime: 106,
        endTime: 110,
    },
    {
        ...dsrpostdoorbossSkills["sacred_sever"],
        startTime: 110,
        endTime: 111,
    },
    {
        ...dsrpostdoorbossSkills["shining_blade"],
        startTime: 111,
        endTime: 114,
    },
    {
        ...dsrpostdoorbossSkills["sacred_sever"],
        startTime: 112,
        endTime: 113,
    },
    {
        ...dsrpostdoorbossSkills["sacred_sever"],
        startTime: 114,
        endTime: 115,
    },
    {
        ...dsrpostdoorbossSkills["sacred_sever"],
        startTime: 116,
        endTime: 117,
    },
    {
        ...dsrpostdoorbossSkills["conviction"],
        startTime: 121,
        endTime: 133,
    },
    {
        ...dsrpostdoorbossSkills["hiemal_storm"],
        startTime: 121,
        endTime: 129,
    },
    {
        ...dsrpostdoorbossSkills["holy_comet_cast"],
        startTime: 121,
        endTime: 133,
    },
    {
        ...dsrpostdoorbossSkills["conviction"],
        startTime: 136,
        endTime: 147,
    },
    {
        ...dsrpostdoorbossSkills["faith_unmoving"],
        startTime: 140,
        endTime: 144,
    },
    {
        ...dsrpostdoorbossSkills["ultimate_end"],
        startTime: 164,
        endTime: 165,
    },
    {
        ...dsrpostdoorbossSkills["broad_swing"],
        startTime: 174,
        endTime: 180,
    },
    {
        ...dsrpostdoorbossSkills["broad_swing"],
        startTime: 182,
        endTime: 188,
    },
    {
        ...dsrpostdoorbossSkills["aetheric_burst"],
        startTime: 190,
        endTime: 196,
    },
    {
        ...dsrpostdoorbossSkills["holy_comet_fall"],
        startTime: 136,
        endTime: 137,
    },
    {
        ...dsrpostdoorbossSkills["holy_comet_fall"],
        startTime: 137,
        endTime: 138,
    },
    {
        ...dsrpostdoorbossSkills["holy_comet_fall"],
        startTime: 138,
        endTime: 139,
    },
    {
        ...dsrpostdoorbossSkills["holy_comet_fall"],
        startTime: 139,
        endTime: 140,
    },
    {
        ...dsrpostdoorbossSkills["holy_comet_fall"],
        startTime: 140,
        endTime: 141,
    },
    {
        ...dsrpostdoorbossSkills["holy_comet_fall"],
        startTime: 141,
        endTime: 142,
    },
    {
        ...dsrpostdoorbossSkills["holy_comet_fall"],
        startTime: 142,
        endTime: 143,
    },
    {
        ...dsrpostdoorbossSkills["final_chorus"],
        startTime: 199,
        endTime: 201,
    },
    {
        ...dsrpostdoorbossSkills["dive_from_grace"],
        startTime: 214,
        endTime: 219,
    },
    {
        ...dsrpostdoorbossSkills["gnash_lash_cast"],
        startTime: 221,
        endTime: 228,
    },
    {
        ...dsrpostdoorbossSkills["gnash_lash"],
        startTime: 230,
        endTime: 231,
    },
    {
        ...dsrpostdoorbossSkills["gnash_lash"],
        startTime: 233,
        endTime: 234,
    },
    {
        ...dsrpostdoorbossSkills["dark_jump_1"],
        startTime: 227,
        endTime: 228,
    },
    {
        ...dsrpostdoorbossSkills["eye_of_the_tyrant"],
        startTime: 227,
        endTime: 228,
    },
    {
        ...dsrpostdoorbossSkills["darkdragon_dive"],
        startTime: 232,
        endTime: 234,
    },
    {
        ...dsrpostdoorbossSkills["geirskogul"],
        startTime: 236,
        endTime: 241,
    },
    {
        ...dsrpostdoorbossSkills["dark_jump_2"],
        startTime: 236,
        endTime: 237,
    },
    {
        ...dsrpostdoorbossSkills["gnash_lash_cast"],
        startTime: 241,
        endTime: 248,
    },
    {
        ...dsrpostdoorbossSkills["gnash_lash"],
        startTime: 251,
        endTime: 252,
    },
    {
        ...dsrpostdoorbossSkills["gnash_lash"],
        startTime: 255,
        endTime: 256,
    },
    {
        ...dsrpostdoorbossSkills["darkdragon_dive"],
        startTime: 241,
        endTime: 244,
    },
    {
        ...dsrpostdoorbossSkills["geirskogul"],
        startTime: 246,
        endTime: 251,
    },
    {
        ...dsrpostdoorbossSkills["dark_jump_3"],
        startTime: 247,
        endTime: 248,
    },
    {
        ...dsrpostdoorbossSkills["eye_of_the_tyrant"],
        startTime: 248,
        endTime: 249,
    },
    {
        ...dsrpostdoorbossSkills["darkdragon_dive"],
        startTime: 252,
        endTime: 255,
    },
    {
        ...dsrpostdoorbossSkills["geirskogul"],
        startTime: 257,
        endTime: 262,
    },
    {
        ...dsrpostdoorbossSkills["drachenlance"],
        startTime: 264,
        endTime: 268,
    },
    {
        ...dsrpostdoorbossSkills["darkdragon_dive"],
        startTime: 269,
        endTime: 274,
    },
    {
        ...dsrpostdoorbossSkills["geirskogul"],
        startTime: 277,
        endTime: 281,
    },
    {
        ...dsrpostdoorbossSkills["soul_tether"],
        startTime: 277,
        endTime: 281,
    },
    {
        ...dsrpostdoorbossSkills["drachenlance"],
        startTime: 302,
        endTime: 306,
    },
    {
        ...dsrpostdoorbossSkills["revenge_of_the_horde"],
        startTime: 307,
        endTime: 318,
    },
    {
        ...dsrpostdoorbossSkills["soul_of_devotion_friendship"],
        startTime: 329,
        endTime: 335,
    },
    {
        ...dsrpostdoorbossSkills["resentment"],
        startTime: 339,
        endTime: 340,
    },
    {
        ...dsrpostdoorbossSkills["hatebound"],
        startTime: 345,
        endTime: 348,
    },
    {
        ...dsrpostdoorbossSkills["flare_nova_star"],
        startTime: 349,
        endTime: 379,
    },
    {
        ...dsrpostdoorbossSkills["mirage_dive"],
        startTime: 371,
        endTime: 374,
    },
    {
        ...dsrpostdoorbossSkills["mirage_dive"],
        startTime: 379,
        endTime: 380,
    },
    {
        ...dsrpostdoorbossSkills["mirage_dive"],
        startTime: 384,
        endTime: 385,
    },
    {
        ...dsrpostdoorbossSkills["mirage_dive"],
        startTime: 390,
        endTime: 391,
    },
    {
        ...dsrpostdoorbossSkills["steep_in_rage"],
        startTime: 394,
        endTime: 400,
    },
    {
        ...dsrpostdoorbossSkills["spear_of_the_fury"],
        startTime: 431,
        endTime: 433,
    },
    {
        ...dsrpostdoorbossSkills["planar_prison"],
        startTime: 423,
        endTime: 424,
    },
    {
        ...dsrpostdoorbossSkills["pure_of_heart"],
        startTime: 423,
        endTime: 459,
    },
    {
        ...dsrpostdoorbossSkills["shockwave_1"],
        startTime: 434,
        endTime: 474,
    },
    {
        ...dsrpostdoorbossSkills["brightwing"],
        startTime: 437,
        endTime: 438,
    },
    {
        ...dsrpostdoorbossSkills["brightwing"],
        startTime: 441,
        endTime: 442,
    },
    {
        ...dsrpostdoorbossSkills["brightwing"],
        startTime: 445,
        endTime: 446,
    },
    {
        ...dsrpostdoorbossSkills["brightwing"],
        startTime: 449,
        endTime: 450,
    },
    {
        ...dsrpostdoorbossSkills["skyblind"],
        startTime: 444,
        endTime: 445,
    },
    {
        ...dsrpostdoorbossSkills["skyblind"],
        startTime: 448,
        endTime: 449,
    },
    {
        ...dsrpostdoorbossSkills["skyblind"],
        startTime: 452,
        endTime: 453,
    },
    {
        ...dsrpostdoorbossSkills["skyblind"],
        startTime: 456,
        endTime: 457,
    },
    {
        ...dsrpostdoorbossSkills["pierce"],
        startTime: 463,
        endTime: 474,
    },
    {
        ...dsrpostdoorbossSkills["incarnation"],
        startTime: 489,
        endTime: 493,
    },
    {
        ...dsrpostdoorbossSkills["the_dragons_eye"],
        startTime: 496,
        endTime: 499,
    },
    {
        ...dsrpostdoorbossSkills["wrath_of_the_heavens"],
        startTime: 514,
        endTime: 518,
    },
    {
        ...dsrpostdoorbossSkills["twisting_dive"],
        startTime: 522,
        endTime: 528,
    },
    {
        ...dsrpostdoorbossSkills["chain_lightning"],
        startTime: 525,
        endTime: 526,
    },
    {
        ...dsrpostdoorbossSkills["skyward_leap_1"],
        startTime: 527,
        endTime: 528,
    },
    {
        ...dsrpostdoorbossSkills["spiral_pierce"],
        startTime: 527,
        endTime: 528,
    },
    {
        ...dsrpostdoorbossSkills["ascalons_mercy_revealed"],
        startTime: 531,
        endTime: 534,
    },
    {
        ...dsrpostdoorbossSkills["altar_flare"],
        startTime: 534,
        endTime: 542,
    },
    {
        ...dsrpostdoorbossSkills["liquid_heaven"],
        startTime: 534,
        endTime: 540,
    },
    {
        ...dsrpostdoorbossSkills["cauterize_1"],
        startTime: 535,
        endTime: 539,
    },
    {
        ...dsrpostdoorbossSkills["empty_dimension"],
        startTime: 536,
        endTime: 541,
    },
    {
        ...dsrpostdoorbossSkills["lightning_storm"],
        startTime: 540,
        endTime: 541,
    },
    {
        ...dsrpostdoorbossSkills["ancient_quaga"],
        startTime: 542,
        endTime: 548,
    },
    {
        ...dsrpostdoorbossSkills["heavenly_heel"],
        startTime: 552,
        endTime: 556,
    },
    {
        ...dsrpostdoorbossSkills["ascalons_might"],
        startTime: 559,
        endTime: 563,
    },
    {
        ...dsrpostdoorbossSkills["death_of_the_heavens"],
        startTime: 570,
        endTime: 574,
    },
    {
        ...dsrpostdoorbossSkills["deathstorm"],
        startTime: 580,
        endTime: 581,
    },
    {
        ...dsrpostdoorbossSkills["heavy_impact"],
        startTime: 582,
        endTime: 594,
    },
    {
        ...dsrpostdoorbossSkills["spear_of_the_fury_2"],
        startTime: 584,
        endTime: 590,
    },
    {
        ...dsrpostdoorbossSkills["lightning_storm"],
        startTime: 584,
        endTime: 590,
    },
    {
        ...dsrpostdoorbossSkills["twisting_dive"],
        startTime: 584,
        endTime: 590,
    },
    {
        ...dsrpostdoorbossSkills["cauterize_1"],
        startTime: 584,
        endTime: 590,
    },
    {
        ...dsrpostdoorbossSkills["wings_of_salvation"],
        startTime: 590,
        endTime: 600,
    },
    {
        ...dsrpostdoorbossSkills["heavensflame"],
        startTime: 598,
        endTime: 605,
    },
    {
        ...dsrpostdoorbossSkills["the_dragons_gaze_glory"],
        startTime: 598,
        endTime: 608,
    },
    {
        ...dsrpostdoorbossSkills["faith_unmoving"],
        startTime: 599,
        endTime: 608,
    },
    {
        ...dsrpostdoorbossSkills["holy_meteors"],
        startTime: 613,
        endTime: 628,
    },
    {
        ...dsrpostdoorbossSkills["ancient_quaga"],
        startTime: 636,
        endTime: 642,
    },
    {
        ...dsrpostdoorbossSkills["heavenly_heel"],
        startTime: 648,
        endTime: 652,
    },
    {
        ...dsrpostdoorbossSkills["ascalons_might"],
        startTime: 655,
        endTime: 659,
    },
    {
        ...dsrpostdoorbossSkills["aetheric_burst"],
        startTime: 664,
        endTime: 670,
    },
    {
        ...dsrpostdoorbossSkills["dread_wyrmsbreath"],
        startTime: 686,
        endTime: 692,
    },
    {
        ...dsrpostdoorbossSkills["great_wyrmsbreath"],
        startTime: 686,
        endTime: 692,
    },
    {
        ...dsrpostdoorbossSkills["dark_staggering_breath"],
        startTime: 692,
        endTime: 693,
    },
    {
        ...dsrpostdoorbossSkills["holy_staggering_breath"],
        startTime: 692,
        endTime: 693,
    },
    {
        ...dsrpostdoorbossSkills["mortal_vow"],
        startTime: 699,
        endTime: 700,
    },
    {
        ...dsrpostdoorbossSkills["akh_afah"],
        startTime: 703,
        endTime: 711,
    },
    {
        ...dsrpostdoorbossSkills["hallowed_wings"],
        startTime: 717,
        endTime: 725,
    },
    {
        ...dsrpostdoorbossSkills["cauterize"],
        startTime: 721,
        endTime: 726,
    },
    {
        ...dsrpostdoorbossSkills["hallowed_plume"],
        startTime: 725,
        endTime: 726,
    },
    {
        ...dsrpostdoorbossSkills["mortal_vow_expires"],
        startTime: 734,
        endTime: 735,
    },
    {
        ...dsrpostdoorbossSkills["wroth_flames"],
        startTime: 737,
        endTime: 740,
    },
    {
        ...dsrpostdoorbossSkills["akh_morn"],
        startTime: 743,
        endTime: 751,
    },
    {
        ...dsrpostdoorbossSkills["cauterize"],
        startTime: 746,
        endTime: 751,
    },
    {
        ...dsrpostdoorbossSkills["hot_tail_wing"],
        startTime: 757,
        endTime: 764,
    },
    {
        ...dsrpostdoorbossSkills["fire_debuffs_expire"],
        startTime: 764,
        endTime: 765,
    },
    {
        ...dsrpostdoorbossSkills["mortal_vow_expires"],
        startTime: 768,
        endTime: 769,
    },
    {
        ...dsrpostdoorbossSkills["akh_afah"],
        startTime: 773,
        endTime: 781,
    },
    {
        ...dsrpostdoorbossSkills["hallowed_wings"],
        startTime: 785,
        endTime: 793,
    },
    {
        ...dsrpostdoorbossSkills["hot_tail_wing"],
        startTime: 787,
        endTime: 794,
    },
    {
        ...dsrpostdoorbossSkills["hallowed_plume"],
        startTime: 793,
        endTime: 794,
    },
    {
        ...dsrpostdoorbossSkills["mortal_vow_expires"],
        startTime: 801,
        endTime: 802,
    },
    {
        ...dsrpostdoorbossSkills["dread_wyrmsbreath"],
        startTime: 806,
        endTime: 813,
    },
    {
        ...dsrpostdoorbossSkills["great_wyrmsbreath"],
        startTime: 806,
        endTime: 813,
    },
    {
        ...dsrpostdoorbossSkills["dark_staggering_breath"],
        startTime: 813,
        endTime: 814,
    },
    {
        ...dsrpostdoorbossSkills["holy_staggering_breath"],
        startTime: 813,
        endTime: 814,
    },
    {
        ...dsrpostdoorbossSkills["cauterize"],
        startTime: 821,
        endTime: 826,
    },
    {
        ...dsrpostdoorbossSkills["touchdown"],
        startTime: 831,
        endTime: 832,
    },
    {
        ...dsrpostdoorbossSkills["mortal_vow_expires"],
        startTime: 835,
        endTime: 836,
    },
    {
        ...dsrpostdoorbossSkills["revenge_of_the_horde"],
        startTime: 834,
        endTime: 858,
    },
    {
        ...dsrpostdoorbossSkills["resentment"],
        startTime: 864,
        endTime: 865,
    },
    {
        ...dsrpostdoorbossSkills["shockwave"],
        startTime: 881,
        endTime: 882,
    },
    {
        ...dsrpostdoorbossSkills["alternative_end"],
        startTime: 897,
        endTime: 898,
    },
    {
        ...dsrpostdoorbossSkills["exaflares_edge"],
        startTime: 912,
        endTime: 918,
    },
    {
        ...dsrpostdoorbossSkills["flames_ice_of_ascalon"],
        startTime: 917,
        endTime: 918,
    },
    {
        ...dsrpostdoorbossSkills["trinity_tank"],
        startTime: 926,
        endTime: 927,
    },
    {
        ...dsrpostdoorbossSkills["trinity_other"],
        startTime: 926,
        endTime: 927,
    },
    {
        ...dsrpostdoorbossSkills["trinity_tank"],
        startTime: 930,
        endTime: 931,
    },
    {
        ...dsrpostdoorbossSkills["trinity_other"],
        startTime: 930,
        endTime: 931,
    },
    {
        ...dsrpostdoorbossSkills["akh_morns_edge_5"],
        startTime: 933,
        endTime: 940,
    },
    {
        ...dsrpostdoorbossSkills["flames_ice_of_ascalon"],
        startTime: 939,
        endTime: 940,
    },
    {
        ...dsrpostdoorbossSkills["trinity_tank"],
        startTime: 949,
        endTime: 950,
    },
    {
        ...dsrpostdoorbossSkills["trinity_other"],
        startTime: 949,
        endTime: 950,
    },
    {
        ...dsrpostdoorbossSkills["trinity_tank"],
        startTime: 953,
        endTime: 954,
    },
    {
        ...dsrpostdoorbossSkills["trinity_other"],
        startTime: 953,
        endTime: 954,
    },
    {
        ...dsrpostdoorbossSkills["gigaflares_edge"],
        startTime: 956,
        endTime: 964,
    },
    {
        ...dsrpostdoorbossSkills["flames_ice_of_ascalon"],
        startTime: 963,
        endTime: 964,
    },
    {
        ...dsrpostdoorbossSkills["trinity_tank"],
        startTime: 982,
        endTime: 983,
    },
    {
        ...dsrpostdoorbossSkills["trinity_other"],
        startTime: 982,
        endTime: 983,
    },
    {
        ...dsrpostdoorbossSkills["trinity_tank"],
        startTime: 987,
        endTime: 988,
    },
    {
        ...dsrpostdoorbossSkills["trinity_other"],
        startTime: 987,
        endTime: 988,
    },
    {
        ...dsrpostdoorbossSkills["exaflares_edge"],
        startTime: 990,
        endTime: 996,
    },
    {
        ...dsrpostdoorbossSkills["flames_ice_of_ascalon"],
        startTime: 995,
        endTime: 996,
    },
    {
        ...dsrpostdoorbossSkills["trinity_tank"],
        startTime: 1004,
        endTime: 1005,
    },
    {
        ...dsrpostdoorbossSkills["trinity_other"],
        startTime: 1004,
        endTime: 1005,
    },
    {
        ...dsrpostdoorbossSkills["trinity_tank"],
        startTime: 1008,
        endTime: 1009,
    },
    {
        ...dsrpostdoorbossSkills["trinity_other"],
        startTime: 1008,
        endTime: 1009,
    },
    {
        ...dsrpostdoorbossSkills["akh_morns_edge_6"],
        startTime: 1011,
        endTime: 1017,
    },
    {
        ...dsrpostdoorbossSkills["flames_ice_of_ascalon"],
        startTime: 1016,
        endTime: 1017,
    },
    {
        ...dsrpostdoorbossSkills["trinity_tank"],
        startTime: 1030,
        endTime: 1031,
    },
    {
        ...dsrpostdoorbossSkills["trinity_other"],
        startTime: 1030,
        endTime: 1031,
    },
    {
        ...dsrpostdoorbossSkills["trinity_tank"],
        startTime: 1034,
        endTime: 1035,
    },
    {
        ...dsrpostdoorbossSkills["trinity_other"],
        startTime: 1034,
        endTime: 1035,
    },
    {
        ...dsrpostdoorbossSkills["gigaflares_edge"],
        startTime: 1037,
        endTime: 1044,
    },
    {
        ...dsrpostdoorbossSkills["flames_ice_of_ascalon"],
        startTime: 1043,
        endTime: 1044,
    },
    {
        ...dsrpostdoorbossSkills["trinity_tank"],
        startTime: 1070,
        endTime: 1071,
    },
    {
        ...dsrpostdoorbossSkills["trinity_other"],
        startTime: 1070,
        endTime: 1071,
    },
    {
        ...dsrpostdoorbossSkills["trinity_tank"],
        startTime: 1074,
        endTime: 1075,
    },
    {
        ...dsrpostdoorbossSkills["trinity_other"],
        startTime: 1074,
        endTime: 1075,
    },
    {
        ...dsrpostdoorbossSkills["exaflares_edge"],
        startTime: 1077,
        endTime: 1083,
    },
    {
        ...dsrpostdoorbossSkills["flames_ice_of_ascalon"],
        startTime: 1082,
        endTime: 1083,
    },
    {
        ...dsrpostdoorbossSkills["trinity_tank"],
        startTime: 1092,
        endTime: 1093,
    },
    {
        ...dsrpostdoorbossSkills["trinity_other"],
        startTime: 1092,
        endTime: 1093,
    },
    {
        ...dsrpostdoorbossSkills["trinity_tank"],
        startTime: 1096,
        endTime: 1097,
    },
    {
        ...dsrpostdoorbossSkills["trinity_other"],
        startTime: 1096,
        endTime: 1097,
    },
    {
        ...dsrpostdoorbossSkills["akh_morns_edge_7"],
        startTime: 1099,
        endTime: 1105,
    },
    {
        ...dsrpostdoorbossSkills["flames_ice_of_ascalon"],
        startTime: 1104,
        endTime: 1105,
    },
    {
        ...dsrpostdoorbossSkills["trinity_tank"],
        startTime: 1114,
        endTime: 1115,
    },
    {
        ...dsrpostdoorbossSkills["trinity_other"],
        startTime: 1114,
        endTime: 1115,
    },
    {
        ...dsrpostdoorbossSkills["trinity_tank"],
        startTime: 1118,
        endTime: 1119,
    },
    {
        ...dsrpostdoorbossSkills["trinity_other"],
        startTime: 1118,
        endTime: 1119,
    },
    {
        ...dsrpostdoorbossSkills["morn_afahs_edge"],
        startTime: 1121,
        endTime: 1136,
    },
]