import { damageTypes, targets } from '../cooldowns/constants';

export const p10sInfo =
{
    name: "Anabaseios: The Tenth Circle (Savage)",
    abbreviation: "P10S",
    boss: "Pandaemonium",
    length: 635,
    level: 90
}

export const p10sSkills =
{
    ultima: {
        id: "ultima",
        name: "Ultima",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Raidwide with bleed",
        damage: 60000,
    },
    soul_grasp: {
        id: "soul_grasp",
        name: "Soul Grasp",
        damageType: damageTypes.MAGIC,
        target: targets.MT,
        avoidable: false,
        tankbuster: true,
        notes: "Stack tankbuster for 4 hits",
        damage: 60000,
    },
    dividing_wings_cast: {
        id: "dividing_wings_cast",
        name: "Dividing Wings (Cast)",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        damage: 0,
    },
    dividing_wings_damage: {
        id: "dividing_wings_damage",
        name: "Dividing Wings (Damage)",
        damageType: damageTypes.MAGIC,
        target: targets.TETHER,
        avoidable: false,
        notes: "Wide cleave on wing tether targets",
        damage: 34000,
    },
    steel_web_cast: {
        id: "steel_web_cast",
        name: "Steel Web (Cast)",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        damage: 0,
    },
    steel_web_damage: {
        id: "steel_web_damage",
        name: "Steel Web (Damage)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "3-person stacks; stacked players will be tethered together and stuck",
        damage: 68000,
    },
    wicked_step: {
        id: "wicked_step",
        name: "Wicked Step",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: false,
        tankbuster: true,
        notes: "Two tower tankbusters with knockback; applies Stab Wound DoT",
        damage: 90000,
    },
    circles_holy: {
        id: "circles_holy",
        name: "Pandaemon's Holy/Circles of Pandaemonium",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Chariot (Holy) or dynamo (Circles)",
        damage: 55000,
    },
    entangling_web: {
        id: "entangling_web",
        name: "Entangling Web",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Baited AoEs; can be connected to form webs",
        damage: 75000,
    },
    pandaemoniac_pillars: {
        id: "pandaemoniac_pillars",
        name: "Pandaemoniac Pillars",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: false,
        damage: 10000,
    },
    silkspit_cast: {
        id: "silkspit_cast",
        name: "Silkspit (Cast)",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        damage: 0,
    },
    silkspit_damage: {
        id: "silkspit_damage",
        name: "Silkspit (Damage)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Individual AoEs",
        damage: 78000,
    },
    meltdown: {
        id: "meltdown",
        name: "Pandaemoniac Meltdown",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Line stack plus two targeted individual line AoEs",
        damage: 82000,
    },
    daemoniac_bonds_cast: {
        id: "daemoniac_bonds_cast",
        name: "Daemoniac Bonds (Cast)",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Stack/spread debuffs go out",
        damage: 0,
    },
    touchdown: {
        id: "touchdown",
        name: "Touchdown",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Massive AoE makes entire middle platform unsafe",
        damage: 9999999,
    },
    daemoniac_bonds_resolve: {
        id: "daemoniac_bonds_resolve",
        name: "Daemoniac Bonds (Debuff Resolves)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Individual AoEs/partner stacks/4 person stacks resolve",
        damage: 33000,
    },
    pandaemoniac_turrets: {
        id: "pandaemoniac_turrets",
        name: "Pandaemoniac Turrets",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: false,
        damage: 10000,
    },
    peal_of_condemnation: {
        id: "peal_of_condemnation",
        name: "Peal of Condemnation",
        damageType: damageTypes.MAGIC,
        target: targets.PROXIMITY_CLOSE,
        avoidable: false,
        notes: "Line AoE with KB targeted on closest player; all players hit receive Magic Vuln Up; closest player receives longer Dark Vuln Up",
        damage: 78000,
    },
    pandaemoniac_ray: {
        id: "pandaemoniac_ray",
        name: "Pandaemoniac Ray",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Cleaves W/E half of arena followed by multiple narrow horizontal line AoEs",
        damage: 90000,
    },
    harrowing_hell: {
        id: "harrowing_hell",
        name: "Harrowing Hell",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Wild Charge hits with increasing damage",
        damage: 55000,
    },
    harrowing_hell_kb: {
        id: "harrowing_hell_kb",
        name: "Harrowing Hell (Knockback)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Final hit with KB",
        damage: 72000,
    },
    parted_plumes: {
        id: "parted_plumes",
        name: "Parted Plumes",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Rotating conal AoEs",
        damage: 90000,
    },
    harrowing_hell_enrage: {
        id: "harrowing_hell_enrage",
        name: "Harrowing Hell (Enrage)",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Soft enrage; damage continues until you die",
        damage: 9999999,
    },
    pandaemoniac_web: {
        id: "pandaemoniac_web",
        name: "Pandaemoniac Web",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Combines Steel Web + Entangling Web",
        damage: 0,
    },
}

export const p10sTimeline =
[
    {
        ...p10sSkills["ultima"],
        startTime: 8,
        endTime: 13,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 18,
        endTime: 23,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 24,
        endTime: 25,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 26,
        endTime: 27,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 27,
        endTime: 28,
    },
    {
        ...p10sSkills["dividing_wings_cast"],
        startTime: 31,
        endTime: 34,
    },
    {
        ...p10sSkills["steel_web_cast"],
        startTime: 37,
        endTime: 40,
    },
    {
        ...p10sSkills["dividing_wings_damage"],
        startTime: 47,
        endTime: 48,
    },
    {
        ...p10sSkills["steel_web_damage"],
        startTime: 47,
        endTime: 48,
    },
    {
        ...p10sSkills["circles_holy"],
        startTime: 54,
        endTime: 58,
    },
    {
        ...p10sSkills["wicked_step"],
        startTime: 61,
        endTime: 68,
    },
    {
        ...p10sSkills["entangling_web"],
        startTime: 75,
        endTime: 78,
    },
    {
        ...p10sSkills["pandaemoniac_pillars"],
        startTime: 90,
        endTime: 95,
    },
    {
        ...p10sSkills["circles_holy"],
        startTime: 98,
        endTime: 102,
    },
    {
        ...p10sSkills["silkspit_cast"],
        startTime: 104,
        endTime: 107,
    },
    {
        ...p10sSkills["silkspit_damage"],
        startTime: 116,
        endTime: 117,
    },
    {
        ...p10sSkills["daemoniac_bonds_cast"],
        startTime: 119,
        endTime: 122,
    },
    {
        ...p10sSkills["meltdown"],
        startTime: 126,
        endTime: 131,
    },
    {
        ...p10sSkills["touchdown"],
        startTime: 135,
        endTime: 143,
    },
    {
        ...p10sSkills["daemoniac_bonds_resolve"],
        startTime: 144,
        endTime: 145,
    },
    {
        ...p10sSkills["daemoniac_bonds_resolve"],
        startTime: 147,
        endTime: 148,
    },
    {
        ...p10sSkills["ultima"],
        startTime: 154,
        endTime: 158,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 163,
        endTime: 168,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 169,
        endTime: 170,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 171,
        endTime: 172,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 172,
        endTime: 173,
    },
    {
        ...p10sSkills["daemoniac_bonds_cast"],
        startTime: 180,
        endTime: 183,
    },
    {
        ...p10sSkills["pandaemoniac_turrets"],
        startTime: 188,
        endTime: 193,
    },
    {
        ...p10sSkills["peal_of_condemnation"],
        startTime: 204,
        endTime: 205,
    },
    {
        ...p10sSkills["peal_of_condemnation"],
        startTime: 209,
        endTime: 210,
    },
    {
        ...p10sSkills["peal_of_condemnation"],
        startTime: 213,
        endTime: 214,
    },
    {
        ...p10sSkills["peal_of_condemnation"],
        startTime: 218,
        endTime: 219,
    },
    {
        ...p10sSkills["daemoniac_bonds_resolve"],
        startTime: 222,
        endTime: 223,
    },
    {
        ...p10sSkills["daemoniac_bonds_resolve"],
        startTime: 225,
        endTime: 226,
    },
    {
        ...p10sSkills["pandaemoniac_ray"],
        startTime: 227,
        endTime: 232,
    },
    {
        ...p10sSkills["ultima"],
        startTime: 243,
        endTime: 248,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 252,
        endTime: 257,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 258,
        endTime: 259,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 260,
        endTime: 261,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 262,
        endTime: 263,
    },
    {
        ...p10sSkills["wicked_step"],
        startTime: 270,
        endTime: 278,
    },
    {
        ...p10sSkills["entangling_web"],
        startTime: 284,
        endTime: 287,
    },
    {
        ...p10sSkills["silkspit_cast"],
        startTime: 294,
        endTime: 297,
    },
    {
        ...p10sSkills["daemoniac_bonds_cast"],
        startTime: 303,
        endTime: 306,
    },
    {
        ...p10sSkills["silkspit_damage"],
        startTime: 307,
        endTime: 308,
    },
    {
        ...p10sSkills["pandaemoniac_pillars"],
        startTime: 310,
        endTime: 315,
    },
    {
        ...p10sSkills["circles_holy"],
        startTime: 318,
        endTime: 321,
    },
    {
        ...p10sSkills["daemoniac_bonds_resolve"],
        startTime: 328,
        endTime: 329,
    },
    {
        ...p10sSkills["pandaemoniac_ray"],
        startTime: 324,
        endTime: 329,
    },
    {
        ...p10sSkills["daemoniac_bonds_resolve"],
        startTime: 332,
        endTime: 333,
    },
    {
        ...p10sSkills["dividing_wings_cast"],
        startTime: 334,
        endTime: 337,
    },
    {
        ...p10sSkills["steel_web_cast"],
        startTime: 340,
        endTime: 343,
    },
    {
        ...p10sSkills["touchdown"],
        startTime: 348,
        endTime: 355,
    },
    {
        ...p10sSkills["dividing_wings_damage"],
        startTime: 355,
        endTime: 356,
    },
    {
        ...p10sSkills["steel_web_damage"],
        startTime: 355,
        endTime: 356,
    },
    {
        ...p10sSkills["meltdown"],
        startTime: 369,
        endTime: 374,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 379,
        endTime: 384,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 384,
        endTime: 385,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 386,
        endTime: 387,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 388,
        endTime: 389,
    },
    {
        ...p10sSkills["dividing_wings_cast"],
        startTime: 400,
        endTime: 403,
    },
    {
        ...p10sSkills["pandaemoniac_web"],
        startTime: 406,
        endTime: 409,
    },
    {
        ...p10sSkills["dividing_wings_damage"],
        startTime: 416,
        endTime: 417,
    },
    {
        ...p10sSkills["steel_web_damage"],
        startTime: 416,
        endTime: 417,
    },
    {
        ...p10sSkills["circles_holy"],
        startTime: 414,
        endTime: 417,
    },
    {
        ...p10sSkills["daemoniac_bonds_cast"],
        startTime: 421,
        endTime: 424,
    },
    {
        ...p10sSkills["harrowing_hell"],
        startTime: 430,
        endTime: 437,
    },
    {
        ...p10sSkills["harrowing_hell"],
        startTime: 438,
        endTime: 439,
    },
    {
        ...p10sSkills["harrowing_hell"],
        startTime: 440,
        endTime: 441,
    },
    {
        ...p10sSkills["harrowing_hell"],
        startTime: 442,
        endTime: 443,
    },
    {
        ...p10sSkills["harrowing_hell"],
        startTime: 443,
        endTime: 444,
    },
    {
        ...p10sSkills["harrowing_hell"],
        startTime: 445,
        endTime: 446,
    },
    {
        ...p10sSkills["harrowing_hell"],
        startTime: 446,
        endTime: 447,
    },
    {
        ...p10sSkills["harrowing_hell"],
        startTime: 447,
        endTime: 448,
    },
    {
        ...p10sSkills["harrowing_hell_kb"],
        startTime: 449,
        endTime: 452,
    },
    {
        ...p10sSkills["daemoniac_bonds_resolve"],
        startTime: 457,
        endTime: 458,
    },
    {
        ...p10sSkills["daemoniac_bonds_resolve"],
        startTime: 460,
        endTime: 461,
    },
    {
        ...p10sSkills["ultima"],
        startTime: 474,
        endTime: 479,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 484,
        endTime: 489,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 490,
        endTime: 491,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 492,
        endTime: 493,
    },
    {
        ...p10sSkills["soul_grasp"],
        startTime: 494,
        endTime: 495,
    },
    {
        ...p10sSkills["wicked_step"],
        startTime: 504,
        endTime: 513,
    },
    {
        ...p10sSkills["entangling_web"],
        startTime: 518,
        endTime: 521,
    },
    {
        ...p10sSkills["parted_plumes"],
        startTime: 540,
        endTime: 552,
    },
    {
        ...p10sSkills["pandaemoniac_ray"],
        startTime: 549,
        endTime: 554,
    },
    {
        ...p10sSkills["circles_holy"],
        startTime: 556,
        endTime: 561,
    },
    {
        ...p10sSkills["silkspit_cast"],
        startTime: 564,
        endTime: 567,
    },
    {
        ...p10sSkills["silkspit_damage"],
        startTime: 577,
        endTime: 578,
    },
    {
        ...p10sSkills["pandaemoniac_pillars"],
        startTime: 580,
        endTime: 585,
    },
    {
        ...p10sSkills["circles_holy"],
        startTime: 587,
        endTime: 591,
    },
    {
        ...p10sSkills["meltdown"],
        startTime: 594,
        endTime: 599,
    },
    {
        ...p10sSkills["harrowing_hell_enrage"],
        startTime: 621,
        endTime: 635,
    },
]