import { damageTypes, targets } from '../cooldowns/constants';

export const p12sp1Info =
{
    name: "Anabaseios: The Twelfth Circle (Savage) | Phase 1",
    abbreviation: "P12S P1",
    boss: "Athena",
    length: 468,
    level: 90
}

export const p12sp1Skills =
{
    on_the_soul: {
        id: "on_the_soul",
        name: "On the Soul",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        damage: 88000,
    },
    paradeigma: {
        id: "paradeigma",
        name: "Paradeigma",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Summons untargetable adds",
        damage: 0,
    },
    white_flame: {
        id: "white_flame",
        name: "White Flame",
        damageType: damageTypes.MAGIC,
        target: targets.PROXIMITY_CLOSE2,
        avoidable: false,
        notes: "Line AoE from add on closest 2 players",
        damage: 58000,
    },
    trinity_of_souls_cast: {
        id: "trinity_of_souls_cast",
        name: "Trinity of Souls (Cast)",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Telegraphs sides for half-room cleaves on wings; bottom to top means she spins 180 degrees with each cleave",
        damage: 80000,
    },
    trinity_of_souls_cleave: {
        id: "trinity_of_souls_cleave",
        name: "Trinity of Souls (Cleave)",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Half-room cleave",
    },
    engravement_of_souls: {
        id: "engravement_of_souls",
        name: "Engravement of Souls",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Debuffs/tethers go out",
        damage: 0,
    },
    polarized_sear: {
        id: "polarized_sear",
        name: "Polarized Sear",
        damageType: damageTypes.MAGIC,
        target: targets.TETHER,
        avoidable: false,
        notes: "Line AoEs on tethered players",
        damage: 65000,
    },
    polarized_glow: {
        id: "polarized_glow",
        name: "Polarized Glow",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "AoEs on players with Astral/Umbralbright Soul debuffs; spawns tower",
        damage: 65000,
    },
    polarized_advance: {
        id: "polarized_advance",
        name: "Polarized Advance",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: false,
        notes: "Towers go off; must be taken by player with opposite debuff",
        damage: 25000,
    },
    ray_of_light: {
        id: "ray_of_light",
        name: "Ray of Light",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Line AoEs from adds; cleaves 1/4 of arena",
        damage: 80000,
    },
    glaukopis: {
        id: "glaukopis",
        name: "Glaukopis",
        damageType: damageTypes.MAGIC,
        target: targets.MT,
        avoidable: false,
        tankbuster: true,
        notes: "Line AoE tankbuster; applies Magic Vuln Up",
        damage: 180000,
    },
    superchain_theory_i: {
        id: "superchain_theory_i",
        name: "Superchain Theory I",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Spawns orbs/chains",
        damage: 0,
    },
    superchain_radiation_emission: {
        id: "superchain_radiation_emission",
        name: "Superchain Radiation/Emission",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Line AoEs from orb; either partner stacks (purple) or solo (orange)",
        damage: 58000,
    },
    polarized_ray: {
        id: "polarized_ray",
        name: "Polarized Ray",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "4-man line stacks on players with Astral/Umbralstrong Soul debuffs; must take line of opposite color of debuff",
        damage: 70000,
    },
    theos_holy: {
        id: "theos_holy",
        name: "Theos's Holy",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "AoEs on players with Heavensflame Soul",
        damage: 58000,
    },
    apo_peridialogos: {
        id: "apo_peridialogos",
        name: "Apodialogos/Peridialogos",
        damageType: damageTypes.PHYS,
        target: targets.MT + " " + targets.OT,
        avoidable: false,
        tankbuster: true,
        notes: "Shared tankbuster with bleed on furthest (Apodialogos) or closest (Peridialogos) player",
        damage: 148000,
    },
    dialogos: {
        id: "dialogos",
        name: "Dialogos",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Stack on closest (Apodialogos) or furthest (Peridialogos) player",
        damage: 80000,
    },
    shock: {
        id: "shock",
        name: "Shock",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: false,
        notes: "Unaspected towers go off",
        damage: 25000,
    },
    unnatural_enchainment: {
        id: "unnatural_enchainment",
        name: "Unnatural Enchainment",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Destroys parts of the arena",
        damage: 0,
    },
    ultima_blade: {
        id: "ultima_blade",
        name: "Ultima Blade",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Forms boundary around arena",
        damage: 82000,
    },
    palladion: {
        id: "palladion",
        name: "Palladion",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Limit cut dashes to be taken by two players; damage based on proximity to last dash",
        damage: 60000,
    },
    white_flame_clear_cut: {
        id: "white_flame_clear_cut",
        name: "White Flame/Clear Cut",
        damageType: damageTypes.MAGIC,
        target: targets.PROXIMITY_CLOSE2,
        avoidable: false,
        notes: "8 adds spawn mid one after the other and either do line AoEs on the two nearest players or a small 270-degree point blank cleave; exact order/timing is random",
        damage: 58000,
    },
    theos_ultima: {
        id: "theos_ultima",
        name: "Theos's Ultima",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        damage: 120000,
    },
    superchain_theory_iia: {
        id: "superchain_theory_iia",
        name: "Superchain Theory IIA",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Spawns orbs/chains",
        damage: 0,
    },
    superchain_theory_iib: {
        id: "superchain_theory_iib",
        name: "Superchain Theory IIB",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Spawns orbs/chains",
        damage: 0,
    },
    parthenos: {
        id: "parthenos",
        name: "Parthenos",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Baited line AoE through boss's hitbox",
        damage: 100000,
    },
    theos_ultima_enrage: {
        id: "theos_ultima_enrage",
        name: "Theos's Ultima (Enrage)",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Boss goes untargetable before enrage",
        damage: 999999,
    },
}

export const p12sp1Timeline =
[
    {
        ...p12sp1Skills["on_the_soul"],
        startTime: 7,
        endTime: 12,
    },
    {
        ...p12sp1Skills["paradeigma"],
        startTime: 18,
        endTime: 21,
    },
    {
        ...p12sp1Skills["trinity_of_souls_cast"],
        startTime: 27,
        endTime: 37,
    },
    {
        ...p12sp1Skills["trinity_of_souls_cleave"],
        startTime: 37,
        endTime: 38,
    },
    {
        ...p12sp1Skills["white_flame"],
        startTime: 38,
        endTime: 39,
    },
    {
        ...p12sp1Skills["trinity_of_souls_cleave"],
        startTime: 39,
        endTime: 40,
    },
    {
        ...p12sp1Skills["trinity_of_souls_cleave"],
        startTime: 41,
        endTime: 42,
    },
    {
        ...p12sp1Skills["white_flame"],
        startTime: 42,
        endTime: 43,
    },
    {
        ...p12sp1Skills["paradeigma"],
        startTime: 55,
        endTime: 58,
    },
    {
        ...p12sp1Skills["engravement_of_souls"],
        startTime: 62,
        endTime: 66,
    },
    {
        ...p12sp1Skills["polarized_sear"],
        startTime: 74,
        endTime: 75,
    },
    {
        ...p12sp1Skills["polarized_glow"],
        startTime: 75,
        endTime: 76,
    },
    {
        ...p12sp1Skills["polarized_advance"],
        startTime: 78,
        endTime: 79,
    },
    {
        ...p12sp1Skills["ray_of_light"],
        startTime: 76,
        endTime: 82,
    },
    {
        ...p12sp1Skills["on_the_soul"],
        startTime: 84,
        endTime: 89,
    },
    {
        ...p12sp1Skills["glaukopis"],
        startTime: 93,
        endTime: 98,
    },
    {
        ...p12sp1Skills["glaukopis"],
        startTime: 100,
        endTime: 101,
    },
    {
        ...p12sp1Skills["superchain_theory_i"],
        startTime: 112,
        endTime: 117,
    },
    {
        ...p12sp1Skills["engravement_of_souls"],
        startTime: 120,
        endTime: 124,
    },
    {
        ...p12sp1Skills["superchain_radiation_emission"],
        startTime: 128,
        endTime: 129,
    },
    {
        ...p12sp1Skills["polarized_ray"],
        startTime: 135,
        endTime: 136,
    },
    {
        ...p12sp1Skills["polarized_glow"],
        startTime: 144,
        endTime: 145,
    },
    {
        ...p12sp1Skills["theos_holy"],
        startTime: 145,
        endTime: 146,
    },
    {
        ...p12sp1Skills["polarized_advance"],
        startTime: 147,
        endTime: 148,
    },
    {
        ...p12sp1Skills["trinity_of_souls_cast"],
        startTime: 149,
        endTime: 159,
    },
    {
        ...p12sp1Skills["trinity_of_souls_cleave"],
        startTime: 159,
        endTime: 160,
    },
    {
        ...p12sp1Skills["trinity_of_souls_cleave"],
        startTime: 161,
        endTime: 162,
    },
    {
        ...p12sp1Skills["trinity_of_souls_cleave"],
        startTime: 163,
        endTime: 164,
    },
    {
        ...p12sp1Skills["apo_peridialogos"],
        startTime: 167,
        endTime: 172,
    },
    {
        ...p12sp1Skills["dialogos"],
        startTime: 171,
        endTime: 172,
    },
    {
        ...p12sp1Skills["on_the_soul"],
        startTime: 175,
        endTime: 180,
    },
    {
        ...p12sp1Skills["paradeigma"],
        startTime: 194,
        endTime: 197,
    },
    {
        ...p12sp1Skills["engravement_of_souls"],
        startTime: 200,
        endTime: 204,
    },
    {
        ...p12sp1Skills["unnatural_enchainment"],
        startTime: 207,
        endTime: 214,
    },
    {
        ...p12sp1Skills["shock"],
        startTime: 207,
        endTime: 214,
    },
    {
        ...p12sp1Skills["polarized_sear"],
        startTime: 214,
        endTime: 215,
    },
    {
        ...p12sp1Skills["polarized_glow"],
        startTime: 221,
        endTime: 222,
    },
    {
        ...p12sp1Skills["white_flame"],
        startTime: 222,
        endTime: 223,
    },
    {
        ...p12sp1Skills["polarized_advance"],
        startTime: 224,
        endTime: 225,
    },
    {
        ...p12sp1Skills["on_the_soul"],
        startTime: 226,
        endTime: 231,
    },
    {
        ...p12sp1Skills["glaukopis"],
        startTime: 238,
        endTime: 243,
    },
    {
        ...p12sp1Skills["glaukopis"],
        startTime: 246,
        endTime: 247,
    },
    {
        ...p12sp1Skills["ultima_blade"],
        startTime: 268,
        endTime: 269,
    },
    {
        ...p12sp1Skills["palladion"],
        startTime: 291,
        endTime: 292,
    },
    {
        ...p12sp1Skills["palladion"],
        startTime: 294,
        endTime: 295,
    },
    {
        ...p12sp1Skills["palladion"],
        startTime: 297,
        endTime: 298,
    },
    {
        ...p12sp1Skills["palladion"],
        startTime: 300,
        endTime: 301,
    },
    {
        ...p12sp1Skills["palladion"],
        startTime: 303,
        endTime: 304,
    },
    {
        ...p12sp1Skills["palladion"],
        startTime: 306,
        endTime: 307,
    },
    {
        ...p12sp1Skills["palladion"],
        startTime: 309,
        endTime: 310,
    },
    {
        ...p12sp1Skills["palladion"],
        startTime: 312,
        endTime: 313,
    },
    {
        ...p12sp1Skills["white_flame_clear_cut"],
        startTime: 293,
        endTime: 317,
    },
    {
        ...p12sp1Skills["theos_ultima"],
        startTime: 328,
        endTime: 335,
    },
    {
        ...p12sp1Skills["superchain_theory_iia"],
        startTime: 349,
        endTime: 354,
    },
    {
        ...p12sp1Skills["trinity_of_souls_cast"],
        startTime: 357,
        endTime: 367,
    },
    {
        ...p12sp1Skills["trinity_of_souls_cleave"],
        startTime: 367,
        endTime: 368,
    },
    {
        ...p12sp1Skills["superchain_radiation_emission"],
        startTime: 367,
        endTime: 368,
    },
    {
        ...p12sp1Skills["trinity_of_souls_cleave"],
        startTime: 369,
        endTime: 370,
    },
    {
        ...p12sp1Skills["trinity_of_souls_cleave"],
        startTime: 372,
        endTime: 373,
    },
    {
        ...p12sp1Skills["superchain_radiation_emission"],
        startTime: 375,
        endTime: 376,
    },
    {
        ...p12sp1Skills["apo_peridialogos"],
        startTime: 377,
        endTime: 382,
    },
    {
        ...p12sp1Skills["dialogos"],
        startTime: 381,
        endTime: 382,
    },
    {
        ...p12sp1Skills["on_the_soul"],
        startTime: 385,
        endTime: 390,
    },
    {
        ...p12sp1Skills["superchain_theory_iib"],
        startTime: 399,
        endTime: 404,
    },
    {
        ...p12sp1Skills["paradeigma"],
        startTime: 408,
        endTime: 411,
    },
    {
        ...p12sp1Skills["parthenos"],
        startTime: 416,
        endTime: 421,
    },
    {
        ...p12sp1Skills["superchain_radiation_emission"],
        startTime: 424,
        endTime: 425,
    },
    {
        ...p12sp1Skills["ray_of_light"],
        startTime: 426,
        endTime: 427,
    },
    {
        ...p12sp1Skills["superchain_radiation_emission"],
        startTime: 433,
        endTime: 434,
    },
    {
        ...p12sp1Skills["unnatural_enchainment"],
        startTime: 429,
        endTime: 436,
    },
    {
        ...p12sp1Skills["on_the_soul"],
        startTime: 440,
        endTime: 445,
    },
    {
        ...p12sp1Skills["on_the_soul"],
        startTime: 448,
        endTime: 453,
    },
    {
        ...p12sp1Skills["theos_ultima_enrage"],
        startTime: 461,
        endTime: 468,
    },
]