import { damageTypes, targets } from '../cooldowns/constants';

export const p12sp2Info =
{
    name: "Anabaseios: The Twelfth Circle (Savage) | Phase 2",
    abbreviation: "P12S P2",
    boss: "Pallas Athena",
    length: 523,
    level: 90
}

export const p12sp2Skills =
{
    ultima: {
        id: "ultima",
        name: "Ultima",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        damage: 88000,
    },
    palladian_grasp: {
        id: "palladian_grasp",
        name: "Palladian Grasp",
        damageType: damageTypes.PHYS,
        target: targets.MT,
        avoidable: false,
        tankbuster: true,
        notes: "Two-hit tankbuster that cleaves the half of the arena the tank is on; applies Phys Vuln Up",
        damage: 200000,
    },
    gaiaochos: {
        id: "gaiaochos",
        name: "Gaiaochos",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Enter the UAV zone",
        damage: 98000,
    },
    summon_darkness: {
        id: "summon_darkness",
        name: "Summon Darkness",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Summons untargetable adds",
        damage: 0,
    },
    ultima_ray: {
        id: "ultima_ray",
        name: "Ultima Ray",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Line AoE from adds",
        damage: 80000,
    },
    missing_link: {
        id: "missing_link",
        name: "Missing Link",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: true,
        notes: "Tethers DPS to supports; breaks if stretched, damage & damage down if not broken",
        damage: 80000,
    },
    demi_parhelion: {
        id: "demi_parhelion",
        name: "Demi Parhelion",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Spawns circle AoEs; resolution depends on Geocentrism telegraph",
        damage: 0,
    },
    geocentrism: {
        id: "geocentrism",
        name: "Geocentrism",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Circle AoEs expand leaving horizontal/vertical/donut safe spots at end of cast based on tentacle position",
        damage: 80000,
    },
    divine_excoriation: {
        id: "divine_excoriation",
        name: "Divine Excoriation",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Small AoEs on all players",
        damage: 60000,
    },
    classical_concepts: {
        id: "classical_concepts",
        name: "The Classical Concepts",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Spawns shapes",
        damage: 100000,
    },
    aspect_effect: {
        id: "aspect_effect",
        name: "Aspect Effect",
        damageType: damageTypes.MAGIC,
        target: targets.TETHER,
        avoidable: false,
        notes: "Damage from tether spawned after blocking square/triangle",
        damage: 52000,
    },
    palladian_ray: {
        id: "palladian_ray",
        name: "Palladian Ray",
        damageType: damageTypes.MAGIC,
        target: targets.PROXIMITY_NEAR4,
        avoidable: false,
        notes: "Persistent cones on four closest players from two tentacles",
        damage: 35000,
    },
    crush_helm_small: {
        id: "crush_helm_small",
        name: "Crush Helm (Debuff)",
        damageType: damageTypes.PHYS,
        target: targets.TANKS,
        avoidable: false,
        tankbuster: true,
        notes: "Four small hits; each applies cleansable Crush Vuln Up",
        damage: 25000,
    },
    crush_helm_big: {
        id: "crush_helm_big",
        name: "Crush Helm (Big)",
        damageType: damageTypes.PHYS,
        target: targets.TANKS,
        avoidable: false,
        tankbuster: true,
        notes: "Main tankbuster",
        damage: 135000,
    },
    caloric_theory: {
        id: "caloric_theory",
        name: "Caloric Theory",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Fire/wind debuffs go out",
        damage: 60000,
    },
    pyre_pulse: {
        id: "pyre_pulse",
        name: "Pyre Pulse",
        damageType: damageTypes.MAGIC,
        target: targets.DEBUFF,
        avoidable: false,
        notes: "Fire debuffs expire into AoE; must be shared with one other person",
        damage: 64000,
    },
    dynamic_atmosphere: {
        id: "dynamic_atmosphere",
        name: "Dynamic Atmosphere",
        damageType: damageTypes.MAGIC,
        target: targets.DEBUFF,
        avoidable: false,
        notes: "Wind debuffs expire into AoE; KB on anyone else hit",
        damage: 60000,
    },
    ekpyrosis_cast: {
        id: "ekpyrosis_cast",
        name: "Ekpyrosis (Cast)",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Spawns proximity AoEs and exaflares",
        damage: 0,
    },
    ekpyrosis_exas: {
        id: "ekpyrosis_exas",
        name: "Ekpyrosis (Exaflares)",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Exaflares start moving",
        damage: 80000,
    },
    ekpyrosis_proximity: {
        id: "ekpyrosis_proximity",
        name: "Ekpyrosis (Proximity)",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: false,
        notes: "Proximity AoEs go off",
        damage: 64000,
    },
    ekpyrosis_aoes: {
        id: "ekpyrosis_aoes",
        name: "Ekpyrosis (AoEs)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Individual AoEs go off",
        damage: 25000,
    },
    pangenesis: {
        id: "pangenesis",
        name: "Pangenesis",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Light/dark and DNA debuffs go out",
        damage: 100000,
    },
    pantheos: {
        id: "pantheos",
        name: "Pantheos",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Spawns three sets of towers",
        damage: 0,
    },
    polarized_advent: {
        id: "polarized_advent",
        name: "Polarized Advent",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: false,
        notes: "Towers go off; need two people with no/opposite debuff to soak",
        damage: 30000,
    },
    factor_in: {
        id: "factor_in",
        name: "Factor In",
        damageType: damageTypes.MAGIC,
        target: targets.TETHER,
        avoidable: false,
        notes: "Blobs hit tethered target in huge AoE",
        damage: 75000,
    },
    panta_rhei: {
        id: "panta_rhei",
        name: "Panta Rhei",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Flips shapes horizontally and vertically",
        damage: 0,
    },
    entropic_excess: {
        id: "entropic_excess",
        name: "Entropic Excess",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Hot potato debuff; drops AoE with each pass",
        damage: 0,
    },
    ultima_blow: {
        id: "ultima_blow",
        name: "Ultima Blow",
        damageType: damageTypes.MAGIC,
        target: targets.TETHER,
        avoidable: false,
        notes: "Proximity-based damage from tethered add; each tethered player needs a second player between them and the add to help soak",
        damage: 55000,
    },
    ignorabimus: {
        id: "ignorabimus",
        name: "Ignorabimus",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
        damage: 999999,
    },
}

export const p12sp2Timeline =
[
    {
        ...p12sp2Skills["ultima"],
        startTime: 6,
        endTime: 11,
    },
    {
        ...p12sp2Skills["palladian_grasp"],
        startTime: 18,
        endTime: 23,
    },
    {
        ...p12sp2Skills["palladian_grasp"],
        startTime: 26,
        endTime: 27,
    },
    {
        ...p12sp2Skills["gaiaochos"],
        startTime: 33,
        endTime: 40,
    },
    {
        ...p12sp2Skills["summon_darkness"],
        startTime: 48,
        endTime: 51,
    },
    {
        ...p12sp2Skills["ultima_ray"],
        startTime: 57,
        endTime: 63,
    },
    {
        ...p12sp2Skills["missing_link"],
        startTime: 57,
        endTime: 64,
    },
    {
        ...p12sp2Skills["demi_parhelion"],
        startTime: 70,
        endTime: 73,
    },
    {
        ...p12sp2Skills["geocentrism"],
        startTime: 76,
        endTime: 83,
    },
    {
        ...p12sp2Skills["divine_excoriation"],
        startTime: 83,
        endTime: 84,
    },
    {
        ...p12sp2Skills["ultima"],
        startTime: 88,
        endTime: 93,
    },
    {
        ...p12sp2Skills["classical_concepts"],
        startTime: 101,
        endTime: 108,
    },
    {
        ...p12sp2Skills["aspect_effect"],
        startTime: 123,
        endTime: 124,
    },
    {
        ...p12sp2Skills["palladian_ray"],
        startTime: 128,
        endTime: 130,
    },
    {
        ...p12sp2Skills["ultima"],
        startTime: 138,
        endTime: 143,
    },
    {
        ...p12sp2Skills["crush_helm_small"],
        startTime: 147,
        endTime: 152,
    },
    {
        ...p12sp2Skills["crush_helm_small"],
        startTime: 152,
        endTime: 153,
    },
    {
        ...p12sp2Skills["crush_helm_small"],
        startTime: 153,
        endTime: 154,
    },
    {
        ...p12sp2Skills["crush_helm_small"],
        startTime: 154,
        endTime: 155,
    },
    {
        ...p12sp2Skills["crush_helm_big"],
        startTime: 156,
        endTime: 157,
    },
    {
        ...p12sp2Skills["caloric_theory"],
        startTime: 164,
        endTime: 172,
    },
    {
        ...p12sp2Skills["pyre_pulse"],
        startTime: 184,
        endTime: 185,
    },
    {
        ...p12sp2Skills["pyre_pulse"],
        startTime: 195,
        endTime: 196,
    },
    {
        ...p12sp2Skills["dynamic_atmosphere"],
        startTime: 195,
        endTime: 196,
    },
    {
        ...p12sp2Skills["ekpyrosis_cast"],
        startTime: 203,
        endTime: 207,
    },
    {
        ...p12sp2Skills["ekpyrosis_exas"],
        startTime: 212,
        endTime: 222,
    },
    {
        ...p12sp2Skills["ekpyrosis_proximity"],
        startTime: 213,
        endTime: 214,
    },
    {
        ...p12sp2Skills["ekpyrosis_aoes"],
        startTime: 216,
        endTime: 217,
    },
    {
        ...p12sp2Skills["ultima"],
        startTime: 221,
        endTime: 226,
    },
    {
        ...p12sp2Skills["pangenesis"],
        startTime: 233,
        endTime: 240,
    },
    {
        ...p12sp2Skills["pantheos"],
        startTime: 244,
        endTime: 248,
    },
    {
        ...p12sp2Skills["polarized_advent"],
        startTime: 253,
        endTime: 254,
    },
    {
        ...p12sp2Skills["polarized_advent"],
        startTime: 258,
        endTime: 259,
    },
    {
        ...p12sp2Skills["polarized_advent"],
        startTime: 263,
        endTime: 264,
    },
    {
        ...p12sp2Skills["factor_in"],
        startTime: 275,
        endTime: 276,
    },
    {
        ...p12sp2Skills["palladian_grasp"],
        startTime: 274,
        endTime: 279,
    },
    {
        ...p12sp2Skills["palladian_grasp"],
        startTime: 281,
        endTime: 282,
    },
    {
        ...p12sp2Skills["classical_concepts"],
        startTime: 289,
        endTime: 296,
    },
    {
        ...p12sp2Skills["panta_rhei"],
        startTime: 303,
        endTime: 313,
    },
    {
        ...p12sp2Skills["aspect_effect"],
        startTime: 319,
        endTime: 320,
    },
    {
        ...p12sp2Skills["palladian_ray"],
        startTime: 322,
        endTime: 323,
    },
    {
        ...p12sp2Skills["ultima"],
        startTime: 327,
        endTime: 332,
    },
    {
        ...p12sp2Skills["crush_helm_small"],
        startTime: 337,
        endTime: 342,
    },
    {
        ...p12sp2Skills["crush_helm_small"],
        startTime: 342,
        endTime: 343,
    },
    {
        ...p12sp2Skills["crush_helm_small"],
        startTime: 343,
        endTime: 344,
    },
    {
        ...p12sp2Skills["crush_helm_small"],
        startTime: 344,
        endTime: 345,
    },
    {
        ...p12sp2Skills["crush_helm_big"],
        startTime: 346,
        endTime: 347,
    },
    {
        ...p12sp2Skills["caloric_theory"],
        startTime: 354,
        endTime: 362,
    },
    {
        ...p12sp2Skills["entropic_excess"],
        startTime: 369,
        endTime: 390,
    },
    {
        ...p12sp2Skills["dynamic_atmosphere"],
        startTime: 389,
        endTime: 390,
    },
    {
        ...p12sp2Skills["ekpyrosis_cast"],
        startTime: 388,
        endTime: 392,
    },
    {
        ...p12sp2Skills["ekpyrosis_exas"],
        startTime: 399,
        endTime: 409,
    },
    {
        ...p12sp2Skills["ekpyrosis_proximity"],
        startTime: 399,
        endTime: 400,
    },
    {
        ...p12sp2Skills["ekpyrosis_aoes"],
        startTime: 402,
        endTime: 403,
    },
    {
        ...p12sp2Skills["ultima"],
        startTime: 406,
        endTime: 411,
    },
    {
        ...p12sp2Skills["gaiaochos"],
        startTime: 418,
        endTime: 425,
    },
    {
        ...p12sp2Skills["summon_darkness"],
        startTime: 433,
        endTime: 436,
    },
    {
        ...p12sp2Skills["demi_parhelion"],
        startTime: 440,
        endTime: 443,
    },
    {
        ...p12sp2Skills["missing_link"],
        startTime: 447,
        endTime: 454,
    },
    {
        ...p12sp2Skills["geocentrism"],
        startTime: 446,
        endTime: 453,
    },
    {
        ...p12sp2Skills["ultima_ray"],
        startTime: 452,
        endTime: 453,
    },
    {
        ...p12sp2Skills["divine_excoriation"],
        startTime: 457,
        endTime: 458,
    },
    {
        ...p12sp2Skills["summon_darkness"],
        startTime: 462,
        endTime: 465,
    },
    {
        ...p12sp2Skills["ultima_blow"],
        startTime: 475,
        endTime: 476,
    },
    {
        ...p12sp2Skills["ultima"],
        startTime: 475,
        endTime: 480,
    },
    {
        ...p12sp2Skills["ultima_blow"],
        startTime: 489,
        endTime: 490,
    },
    {
        ...p12sp2Skills["ultima"],
        startTime: 489,
        endTime: 494,
    },
    {
        ...p12sp2Skills["ignorabimus"],
        startTime: 508,
        endTime: 523,
    },
]