import { damageTypes, targets } from '../cooldowns/constants';

export const p6sInfo =
{
    name: "Abyssos: The Sixth Circle (Savage)",
    abbreviation: "P6S",
    boss: "Hegemone",
    length: 639,
    level: 90
}

export const p6sSkills =
{
    dark_4: {
        id: "dark_4",
        name: "Hemitheos's Dark IV",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Heavy-hitting raidwide",
    },
    chelic_synergy: {
        id: "chelic_synergy",
        name: "Chelic Synergy",
        damageType: damageTypes.PHYS,
        target: targets.MT + " + " + targets.OT,
        avoidable: false,
        tankbuster: true,
        notes: "Shared cleave tankbuster",
    },
    aetheric_polyominoid: {
        id: "aetheric_polyominoid",
        name: "Aetheric Polyominoid",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Aetherial nexuses spawn",
    },
    unholy_darkness_cast: {
        id: "unholy_darkness_cast",
        name: "Unholy Darkness (cast)",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Stack markers appear",
    },
    unholy_darkness_resolves: {
        id: "unholy_darkness_resolves",
        name: "Unholy Darkness (resolution)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Stack resolves",
    },
    exocleaver_1: {
        id: "exocleaver_1",
        name: "Exocleaver",
        damageType: damageTypes.MAGIC,
        target: targets.DIRECTIONAL,
        avoidable: true,
        notes: "Protean cleaves",
    },
    exocleaver_2: {
        id: "exocleaver_2",
        name: "Exocleaver",
        damageType: damageTypes.MAGIC,
        target: targets.DIRECTIONAL,
        avoidable: true,
        notes: "Cleaves in gaps between first cleaves",
    },
    pathogenic_cells: {
        id: "pathogenic_cells",
        name: "Pathogenic Cells",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Limit cut",
    },
    aetherial_exchange: {
        id: "aetherial_exchange",
        name: "Aetherial Exchange",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Next mechanic will have swaps",
    },
    exchange_of_agonies: {
        id: "exchange_of_agonies",
        name: "Exchange of Agonies",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Stack/donut/AoE & swap indicators appear",
    },
    choros_ixou_1: {
        id: "choros_ixou_1",
        name: "Choros Ixou",
        damageType: damageTypes.MAGIC,
        target: targets.DIRECTIONAL,
        avoidable: true,
        notes: "N/S or E/W cleaves",
    },
    choros_ixou_2: {
        id: "choros_ixou_2",
        name: "Choros Ixou",
        damageType: damageTypes.MAGIC,
        target: targets.DIRECTIONAL,
        avoidable: true,
        notes: "Untelegraphed cleaves opposite of previous cleaves",
    },
    darkburst: {
        id: "darkburst",
        name: "Darkbust",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Individual AoE",
    },
    dark_perimeter: {
        id: "dark_perimeter",
        name: "Dark Perimeter",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: true,
        notes: "Donut AoE",
    },
    synergy: {
        id: "synergy",
        name: "Synergy",
        damageType: damageTypes.PHYS,
        target: targets.AGGRO_1_2,
        avoidable: false,
        tankbuster: true,
        notes: "Individual busters, swap required",
    },
    transmission: {
        id: "transmission",
        name: "Transmission",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Snakes/claws put on party members",
    },
    chelic_claw_reek_havoc: {
        id: "chelic_claw_reek_havoc",
        name: "Chelic Claw/Reek Havoc",
        damageType: damageTypes.MAGIC,
        target: targets.DIRECTIONAL,
        avoidable: true,
        notes: "Snakes/claws go off",
    },
    polyominoid_sigma: {
        id: "polyominoid_sigma",
        name: "Polyominoid Sigma",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Aetherial nexuses spawn",
    },
    dark_dome_cast: {
        id: "dark_dome_cast",
        name: "Dark Dome (cast)",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Snapshot for AoEs on all party members at cast end",
    },
    dark_dome_resolves: {
        id: "dark_dome_resolves",
        name: "Dark Dome (resolution)",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "AoEs go off",
    },
    dark_ashes_resolves: {
        id: "dark_ashes_resolves",
        name: "Dark Ashes (resolution)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "AoEs go off",
    },
    dark_ashes_cast: {
        id: "dark_ashes_cast",
        name: "Dark Ashes (cast)",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Large AoEs appear on all party members",
    },
    dark_sphere_resolves: {
        id: "dark_sphere_resolves",
        name: "Dark Sphere (resolution)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "AoEs go off",
    },
    dark_sphere_cast: {
        id: "dark_sphere_cast",
        name: "Dark Sphere (cast)",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Large AoEs appear on all party members",
    },
    cachexia_1: {
        id: "cachexia_1",
        name: "Cachexia",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Purple & green (weak to snake/weak to claw) and Aetheronecrosis debuffs go out",
    },
    cachexia_2: {
        id: "cachexia_2",
        name: "Cachexia",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Purple & green (weak to snake/weak to claw) debuffs go out",
    },
    aetheronecrosis_1: {
        id: "aetheronecrosis_1",
        name: "Aetheronecrosis",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "8s debuff AoEs go off",
    },
    aetheronecrosis_2: {
        id: "aetheronecrosis_2",
        name: "Aetheronecrosis",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "12s debuff AoEs go off",
    },
    aetheronecrosis_3: {
        id: "aetheronecrosis_3",
        name: "Aetheronecrosis",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "16s debuff AoEs go off",
    },
    aetheronecrosis_4: {
        id: "aetheronecrosis_4",
        name: "Aetheronecrosis",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "20s debuff AoEs go off",
    },
    glossal_chelic_predation: {
        id: "glossal_chelic_predation",
        name: "Glossal/Chelic Predation",
        damageType: damageTypes.PHYS,
        target: targets.PROXIMITY_CLOSE2,
        avoidable: false,
        notes: "Closest player on each side hit with claw (left side) or snake (right side)",
    },
    dual_predation: {
        id: "dual_predation",
        name: "Dual Predation",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Glossal/chelic predation hits begin",
    },
    ptera_ixou: {
        id: "ptera_ixou",
        name: "Ptera Ixou",
        damageType: damageTypes.PHYS,
        target: targets.DIRECTIONAL,
        avoidable: false,
        notes: "Claw hits entire left/west side of arena, snake hits entire right/east side",
    },
    dark_sphere: {
        id: "dark_sphere",
        name: "Dark Sphere",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Large AoEs on all party members",
    },
    polyominous_dark_4: {
        id: "polyominous_dark_4",
        name: "Polyominous Dark IV",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Unsafe tiles explode",
    },
    either_synergy: {
        id: "either_synergy",
        name: "Chelic Synergy/Synergy",
        damageType: damageTypes.PHYS,
        target: targets.MT + " + " + targets.OT,
        avoidable: false,
        tankbuster: true,
        notes: "Either Chelic Synergy (shared buster) or Synergy (individual busters)",
    },
    dark_4_enrage: {
        id: "dark_4_enrage",
        name: "Hemitheos's Dark IV",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
    },
}

export const p6sTimeline =
    [
        {
            ...p6sSkills["dark_4"],
            startTime: 8,
            endTime: 13,
        },
        {
            ...p6sSkills["chelic_synergy"],
            startTime: 20,
            endTime: 27,
        },
        {
            ...p6sSkills["aetheric_polyominoid"],
            startTime: 37,
            endTime: 41,
        },
        {
            ...p6sSkills["unholy_darkness_cast"],
            startTime: 44,
            endTime: 48,
        },
        {
            ...p6sSkills["exocleaver_1"],
            startTime: 50,
            endTime: 54,
        },
        {
            ...p6sSkills["polyominous_dark_4"],
            startTime: 53,
            endTime: 54,
        },
        {
            ...p6sSkills["unholy_darkness_resolves"],
            startTime: 55,
            endTime: 56,
        },
        {
            ...p6sSkills["exocleaver_2"],
            startTime: 56,
            endTime: 57,
        },
        {
            ...p6sSkills["pathogenic_cells"],
            startTime: 63,
            endTime: 71,
        },
        {
            ...p6sSkills["pathogenic_cells"],
            startTime: 72,
            endTime: 73,
        },
        {
            ...p6sSkills["pathogenic_cells"],
            startTime: 74,
            endTime: 75,
        },
        {
            ...p6sSkills["pathogenic_cells"],
            startTime: 76,
            endTime: 77,
        },
        {
            ...p6sSkills["pathogenic_cells"],
            startTime: 78,
            endTime: 79,
        },
        {
            ...p6sSkills["pathogenic_cells"],
            startTime: 80,
            endTime: 81,
        },
        {
            ...p6sSkills["pathogenic_cells"],
            startTime: 82,
            endTime: 83,
        },
        {
            ...p6sSkills["pathogenic_cells"],
            startTime: 84,
            endTime: 85,
        },
        {
            ...p6sSkills["aetherial_exchange"],
            startTime: 93,
            endTime: 96,
        },
        {
            ...p6sSkills["exchange_of_agonies"],
            startTime: 98,
            endTime: 102,
        },
        {
            ...p6sSkills["choros_ixou_1"],
            startTime: 105,
            endTime: 110,
        },
        {
            ...p6sSkills["darkburst"],
            startTime: 109,
            endTime: 110,
        },
        {
            ...p6sSkills["dark_perimeter"],
            startTime: 109,
            endTime: 110,
        },
        {
            ...p6sSkills["unholy_darkness_resolves"],
            startTime: 109,
            endTime: 110,
        },
        {
            ...p6sSkills["choros_ixou_2"],
            startTime: 112,
            endTime: 113,
        },
        {
            ...p6sSkills["synergy"],
            startTime: 120,
            endTime: 127,
        },
        {
            ...p6sSkills["dark_4"],
            startTime: 135,
            endTime: 140,
        },
        {
            ...p6sSkills["transmission"],
            startTime: 146,
            endTime: 151,
        },
        {
            ...p6sSkills["choros_ixou_1"],
            startTime: 160,
            endTime: 165,
        },
        {
            ...p6sSkills["chelic_claw_reek_havoc"],
            startTime: 165,
            endTime: 166,
        },
        {
            ...p6sSkills["choros_ixou_2"],
            startTime: 166,
            endTime: 167,
        },
        {
            ...p6sSkills["aetherial_exchange"],
            startTime: 174,
            endTime: 177,
        },
        {
            ...p6sSkills["polyominoid_sigma"],
            startTime: 180,
            endTime: 184,
        },
        {
            ...p6sSkills["dark_dome_cast"],
            startTime: 188,
            endTime: 193,
        },
        {
            ...p6sSkills["polyominous_dark_4"],
            startTime: 197,
            endTime: 198,
        },
        {
            ...p6sSkills["dark_dome_resolves"],
            startTime: 197,
            endTime: 198,
        },
        {
            ...p6sSkills["aetherial_exchange"],
            startTime: 205,
            endTime: 208,
        },
        {
            ...p6sSkills["exchange_of_agonies"],
            startTime: 210,
            endTime: 214,
        },
        {
            ...p6sSkills["exocleaver_1"],
            startTime: 218,
            endTime: 222,
        },
        {
            ...p6sSkills["unholy_darkness_resolves"],
            startTime: 221,
            endTime: 222,
        },
        {
            ...p6sSkills["darkburst"],
            startTime: 221,
            endTime: 222,
        },
        {
            ...p6sSkills["exocleaver_2"],
            startTime: 224,
            endTime: 225,
        },
        {
            ...p6sSkills["synergy"],
            startTime: 231,
            endTime: 237,
        },
        {
            ...p6sSkills["dark_4"],
            startTime: 245,
            endTime: 250,
        },
        {
            ...p6sSkills["aetherial_exchange"],
            startTime: 257,
            endTime: 260,
        },
        {
            ...p6sSkills["polyominoid_sigma"],
            startTime: 262,
            endTime: 266,
        },
        {
            ...p6sSkills["unholy_darkness_cast"],
            startTime: 269,
            endTime: 274,
        },
        {
            ...p6sSkills["polyominous_dark_4"],
            startTime: 279,
            endTime: 280,
        },
        {
            ...p6sSkills["unholy_darkness_resolves"],
            startTime: 279,
            endTime: 280,
        },
        {
            ...p6sSkills["dark_ashes_cast"],
            startTime: 288,
            endTime: 292,
        },
        {
            ...p6sSkills["choros_ixou_1"],
            startTime: 295,
            endTime: 300,
        },
        {
            ...p6sSkills["dark_ashes_resolves"],
            startTime: 299,
            endTime: 300,
        },
        {
            ...p6sSkills["choros_ixou_2"],
            startTime: 302,
            endTime: 303,
        },
        {
            ...p6sSkills["cachexia_1"],
            startTime: 312,
            endTime: 315,
        },
        {
            ...p6sSkills["aetheronecrosis_1"],
            startTime: 323,
            endTime: 324,
        },
        {
            ...p6sSkills["aetheronecrosis_2"],
            startTime: 327,
            endTime: 328,
        },
        {
            ...p6sSkills["aetheronecrosis_3"],
            startTime: 331,
            endTime: 332,
        },
        {
            ...p6sSkills["dual_predation"],
            startTime: 326,
            endTime: 332,
        },
        {
            ...p6sSkills["glossal_chelic_predation"],
            startTime: 332,
            endTime: 333,
        },
        {
            ...p6sSkills["aetheronecrosis_4"],
            startTime: 335,
            endTime: 336,
        },
        {
            ...p6sSkills["glossal_chelic_predation"],
            startTime: 336,
            endTime: 337,
        },
        {
            ...p6sSkills["glossal_chelic_predation"],
            startTime: 340,
            endTime: 341,
        },
        {
            ...p6sSkills["glossal_chelic_predation"],
            startTime: 344,
            endTime: 345,
        },
        {
            ...p6sSkills["ptera_ixou"],
            startTime: 349,
            endTime: 355,
        },
        {
            ...p6sSkills["chelic_synergy"],
            startTime: 363,
            endTime: 370,
        },
        {
            ...p6sSkills["dark_4"],
            startTime: 377,
            endTime: 382,
        },
        {
            ...p6sSkills["aetheric_polyominoid"],
            startTime: 389,
            endTime: 393,
        },
        {
            ...p6sSkills["dark_sphere_cast"],
            startTime: 395,
            endTime: 399,
        },
        {
            ...p6sSkills["dark_dome_cast"],
            startTime: 401,
            endTime: 405,
        },
        {
            ...p6sSkills["dark_sphere_resolves"],
            startTime: 405,
            endTime: 406,
        },
        {
            ...p6sSkills["polyominous_dark_4"],
            startTime: 405,
            endTime: 406,
        },
        {
            ...p6sSkills["dark_dome_resolves"],
            startTime: 409,
            endTime: 410,
        },
        {
            ...p6sSkills["aetherial_exchange"],
            startTime: 418,
            endTime: 421,
        },
        {
            ...p6sSkills["exchange_of_agonies"],
            startTime: 423,
            endTime: 427,
        },
        {
            ...p6sSkills["choros_ixou_1"],
            startTime: 430,
            endTime: 435,
        },
        {
            ...p6sSkills["darkburst"],
            startTime: 434,
            endTime: 435,
        },
        {
            ...p6sSkills["dark_perimeter"],
            startTime: 434,
            endTime: 435,
        },
        {
            ...p6sSkills["unholy_darkness_resolves"],
            startTime: 434,
            endTime: 435,
        },
        {
            ...p6sSkills["choros_ixou_2"],
            startTime: 437,
            endTime: 438,
        },
        {
            ...p6sSkills["aetherial_exchange"],
            startTime: 444,
            endTime: 447,
        },
        {
            ...p6sSkills["polyominoid_sigma"],
            startTime: 450,
            endTime: 454,
        },
        {
            ...p6sSkills["choros_ixou_1"],
            startTime: 461,
            endTime: 466,
        },
        {
            ...p6sSkills["polyominous_dark_4"],
            startTime: 466,
            endTime: 467,
        },
        {
            ...p6sSkills["choros_ixou_2"],
            startTime: 469,
            endTime: 470,
        },
        {
            ...p6sSkills["either_synergy"],
            startTime: 476,
            endTime: 483,
        },
        {
            ...p6sSkills["dark_4"],
            startTime: 490,
            endTime: 495,
        },
        {
            ...p6sSkills["cachexia_2"],
            startTime: 504,
            endTime: 507,
        },
        {
            ...p6sSkills["transmission"],
            startTime: 510,
            endTime: 515,
        },
        {
            ...p6sSkills["aetherial_exchange"],
            startTime: 520,
            endTime: 523,
        },
        {
            ...p6sSkills["polyominoid_sigma"],
            startTime: 525,
            endTime: 529,
        },
        {
            ...p6sSkills["ptera_ixou"],
            startTime: 537,
            endTime: 543,
        },
        {
            ...p6sSkills["dark_sphere_resolves"],
            startTime: 542,
            endTime: 543,
        },
        {
            ...p6sSkills["unholy_darkness_resolves"],
            startTime: 542,
            endTime: 543,
        },
        {
            ...p6sSkills["chelic_claw_reek_havoc"],
            startTime: 543,
            endTime: 544,
        },
        {
            ...p6sSkills["aetheric_polyominoid"],
            startTime: 552,
            endTime: 556,
        },
        {
            ...p6sSkills["dark_dome_cast"],
            startTime: 561,
            endTime: 565,
        },
        {
            ...p6sSkills["polyominous_dark_4"],
            startTime: 568,
            endTime: 569,
        },
        {
            ...p6sSkills["dark_dome_resolves"],
            startTime: 568,
            endTime: 569,
        },
        {
            ...p6sSkills["aetheric_polyominoid"],
            startTime: 577,
            endTime: 581,
        },
        {
            ...p6sSkills["choros_ixou_1"],
            startTime: 586,
            endTime: 591,
        },
        {
            ...p6sSkills["polyominous_dark_4"],
            startTime: 590,
            endTime: 591,
        },
        {
            ...p6sSkills["choros_ixou_2"],
            startTime: 593,
            endTime: 594,
        },
        {
            ...p6sSkills["either_synergy"],
            startTime: 600,
            endTime: 607,
        },
        {
            ...p6sSkills["dark_4"],
            startTime: 614,
            endTime: 619,
        },
        {
            ...p6sSkills["dark_4_enrage"],
            startTime: 629,
            endTime: 639,
        },
    ]