import { damageTypes, targets } from '../cooldowns/constants';

export const p7sInfo =
{
    name: "Abyssos: The Seventh Circle (Savage)",
    abbreviation: "P7S",
    boss: "Agdistis",
    length: 673,
    level: 90
}

export const p7sSkills =
{
    spark_of_life: {
        id: "spark_of_life",
        name: "Spark of Life",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Heavy-hitting raidwide with bleed",
    },
    condensed_dispersed_aero: {
        id: "condensed_dispersed_aero",
        name: "Condensed/Dispersed Aero II",
        damageType: damageTypes.MAGIC,
        target: targets.AGGRO_1_2,
        avoidable: false,
        tankbuster: true,
        notes: "Condensed = one shared buster on MT, dispersed = 2 individual busters",
    },
    blades_of_attis_cast: {
        id: "blades_of_attis_cast",
        name: "Blades of Attis (cast)",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Exaflare indicators spawn",
    },
    immortals_obol: {
        id: "immortals_obol",
        name: "Immortal's Obol",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: false,
        notes: "Proximity damage from center, knocks party in the air",
    },
    blades_of_attis_resolves: {
        id: "blades_of_attis_resolves",
        name: "Blades of Attis (resolution)",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Exaflares move across arena",
    },
    forbidden_fruit: {
        id: "forbidden_fruit",
        name: "Forbidden Fruit",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Untargetable adds spawn",
    },
    bough_of_attis_hit: {
        id: "bough_of_attis_hit",
        name: "Bough of Attis (hit)",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: true,
        notes: "Huge circle AoE at front or back of arena",
    },
    stymphalian_strike: {
        id: "stymphalian_strike",
        name: "Stymphalian Strike",
        damageType: damageTypes.PHYS,
        target: targets.DIRECTIONAL,
        avoidable: true,
        notes: "Birds dash",
    },
    static_moon: {
        id: "static_moon",
        name: "Static Moon",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "AoE on entire platform with yak/ox in center",
    },
    inviolate_bonds: {
        id: "inviolate_bonds",
        name: "Inviolate Bonds",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Two rounds of aero/holy debuffs go out",
    },
    aero_3: {
        id: "aero_3",
        name: "Hemitheos's Aero III",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Individual AoEs as aero debuffs expire",
    },
    holy_3: {
        id: "holy_3",
        name: "Hemitheos's Holy III",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "4-man stack on party member as holy debuff expires",
    },
    bough_of_attis_punch: {
        id: "bough_of_attis_punch",
        name: "Bough of Attis (dash)",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: true,
        notes: "Line cleave as boss punches forward with one arm",
    },
    roots_of_attis: {
        id: "roots_of_attis",
        name: "Roots of Attis",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Bridge(s) destroyed",
    },
    multicast: {
        id: "multicast",
        name: "Multicast",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Indicates next casts will resolve near simultaneously",
    },
    aero_4: {
        id: "aero_4",
        name: "Hemitheos's Aero IV",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: false,
        notes: "KB from center of one platform with small AoE damage",
    },
    holy: {
        id: "holy",
        name: "Hemitheos's Holy",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Individual AoEs on all party members",
    },
    bullish_swipe: {
        id: "bullish_swipe",
        name: "Bullish Swipe",
        damageType: damageTypes.PHYS,
        target: targets.DIRECTIONAL,
        avoidable: true,
        notes: "Baited minotaur cleaves resolve",
    },
    bullish_slash: {
        id: "bullish_slash",
        name: "Bullish Slash",
        damageType: damageTypes.PHYS,
        target: targets.PARTY,
        avoidable: false,
        notes: "Proximity tethers from minotaurs resolve",
    },
    static_path: {
        id: "static_path",
        name: "Static Path",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Lightning tether line AoEs from yak/ox resolve",
    },
    shadow_of_attis: {
        id: "shadow_of_attis",
        name: "Shadow of Attis",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Towers spawn",
    },
    bronze_bellows: {
        id: "bronze_bellows",
        name: "Bronze Bellows",
        damageType: damageTypes.PHYS,
        target: targets.PARTY,
        avoidable: false,
        notes: "Tethered birds dash and knock back any hit",
    },
    burst: {
        id: "burst",
        name: "Burst",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: false,
        notes: "Towers resolve",
    },
    inviolate_purgation: {
        id: "inviolate_purgation",
        name: "Inviolate Purgation",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Four rounds of aero/holy debuffs go out",
    },
    light_of_life: {
        id: "light_of_life",
        name: "Light of Life",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Heavy-hitting raidwide (no bleed)",
    },
    tornado: {
        id: "tornado",
        name: "Hemitheos's Tornado",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Huge delayed AoEs hit where Aero players were standing when last debuffs went off",
    },
    glare_3: {
        id: "glare_3",
        name: "Hemitheos's Glare III",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Huge delayed donut where Holy player was standing when last debuffs went off",
    },
    glare_cast: {
        id: "glare_cast",
        name: "Hemitheos's Glare (cast)",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Chasing AoE indicators appear",
    },
    glare_resolves: {
        id: "glare_resolves",
        name: "Hemitheos's Glare (resolution)",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Chasing AoEs spawn",
    },
    famines_harvest: {
        id: "famines_harvest",
        name: "Famine's Harvest",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Spawns four minotaurs with proximity tethers, two minotaurs with no tethers, and two birds with no tethers",
    },
    deaths_harvest: {
        id: "deaths_harvest",
        name: "Death's Harvest",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Spawns two tethered yaks/oxen, one untethered yak/ox, and two untethered birds",
    },
    wars_harvest: {
        id: "wars_harvest",
        name: "War's Harvest",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Spawns one tethered yak/ox, two tethered minotaurs, and two tethered birds",
    },
    light_of_life_enrage: {
        id: "light_of_life_enrage",
        name: "Light of Life",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
    },
}

export const p7sTimeline =
    [
        {
            ...p7sSkills["spark_of_life"],
            startTime: 8,
            endTime: 12,
        },
        {
            ...p7sSkills["condensed_dispersed_aero"],
            startTime: 19,
            endTime: 27,
        },
        {
            ...p7sSkills["blades_of_attis_cast"],
            startTime: 31,
            endTime: 34,
        },
        {
            ...p7sSkills["immortals_obol"],
            startTime: 37,
            endTime: 44,
        },
        {
            ...p7sSkills["blades_of_attis_resolves"],
            startTime: 46,
            endTime: 58,
        },
        {
            ...p7sSkills["forbidden_fruit"],
            startTime: 55,
            endTime: 58,
        },
        {
            ...p7sSkills["bough_of_attis_hit"],
            startTime: 73,
            endTime: 80,
        },
        {
            ...p7sSkills["holy_3"],
            startTime: 73,
            endTime: 80,
        },
        {
            ...p7sSkills["stymphalian_strike"],
            startTime: 77,
            endTime: 80,
        },
        {
            ...p7sSkills["static_moon"],
            startTime: 77,
            endTime: 80,
        },
        {
            ...p7sSkills["condensed_dispersed_aero"],
            startTime: 84,
            endTime: 92,
        },
        {
            ...p7sSkills["spark_of_life"],
            startTime: 97,
            endTime: 102,
        },
        {
            ...p7sSkills["inviolate_bonds"],
            startTime: 107,
            endTime: 111,
        },
        {
            ...p7sSkills["bough_of_attis_hit"],
            startTime: 115,
            endTime: 122,
        },
        {
            ...p7sSkills["aero_3"],
            startTime: 120,
            endTime: 121,
        },
        {
            ...p7sSkills["holy_3"],
            startTime: 120,
            endTime: 121,
        },
        {
            ...p7sSkills["bough_of_attis_punch"],
            startTime: 129,
            endTime: 130,
        },
        {
            ...p7sSkills["aero_3"],
            startTime: 131,
            endTime: 132,
        },
        {
            ...p7sSkills["holy_3"],
            startTime: 131,
            endTime: 132,
        },
        {
            ...p7sSkills["roots_of_attis"],
            startTime: 135,
            endTime: 138,
        },
        {
            ...p7sSkills["condensed_dispersed_aero"],
            startTime: 149,
            endTime: 156,
        },
        {
            ...p7sSkills["forbidden_fruit"],
            startTime: 161,
            endTime: 165,
        },
        {
            ...p7sSkills["multicast"],
            startTime: 172,
            endTime: 175,
        },
        {
            ...p7sSkills["aero_4"],
            startTime: 175,
            endTime: 181,
        },
        {
            ...p7sSkills["holy"],
            startTime: 180,
            endTime: 185,
        },
        {
            ...p7sSkills["stymphalian_strike"],
            startTime: 183,
            endTime: 186,
        },
        {
            ...p7sSkills["roots_of_attis"],
            startTime: 190,
            endTime: 193,
        },
        {
            ...p7sSkills["forbidden_fruit"],
            startTime: 201,
            endTime: 205,
        },
        {
            ...p7sSkills["static_moon"],
            startTime: 220,
            endTime: 222,
        },
        {
            ...p7sSkills["holy_3"],
            startTime: 214,
            endTime: 223,
        },
        {
            ...p7sSkills["bough_of_attis_hit"],
            startTime: 234,
            endTime: 241,
        },
        {
            ...p7sSkills["bough_of_attis_punch"],
            startTime: 243,
            endTime: 248,
        },
        {
            ...p7sSkills["condensed_dispersed_aero"],
            startTime: 251,
            endTime: 259,
        },
        {
            ...p7sSkills["forbidden_fruit"],
            startTime: 261,
            endTime: 265,
        },
        {
            ...p7sSkills["bullish_swipe"],
            startTime: 283,
            endTime: 286,
        },
        {
            ...p7sSkills["bullish_slash"],
            startTime: 285,
            endTime: 286,
        },
        {
            ...p7sSkills["static_path"],
            startTime: 285,
            endTime: 286,
        },
        {
            ...p7sSkills["blades_of_attis_cast"],
            startTime: 291,
            endTime: 294,
        },
        {
            ...p7sSkills["multicast"],
            startTime: 297,
            endTime: 300,
        },
        {
            ...p7sSkills["aero_4"],
            startTime: 300,
            endTime: 306,
        },
        {
            ...p7sSkills["holy_3"],
            startTime: 303,
            endTime: 309,
        },
        {
            ...p7sSkills["blades_of_attis_resolves"],
            startTime: 307,
            endTime: 318,
        },
        {
            ...p7sSkills["condensed_dispersed_aero"],
            startTime: 316,
            endTime: 323,
        },
        {
            ...p7sSkills["forbidden_fruit"],
            startTime: 329,
            endTime: 333,
        },
        {
            ...p7sSkills["shadow_of_attis"],
            startTime: 341,
            endTime: 342,
        },
        {
            ...p7sSkills["bronze_bellows"],
            startTime: 352,
            endTime: 353,
        },
        {
            ...p7sSkills["burst"],
            startTime: 353,
            endTime: 354,
        },
        {
            ...p7sSkills["spark_of_life"],
            startTime: 357,
            endTime: 362,
        },
        {
            ...p7sSkills["immortals_obol"],
            startTime: 370,
            endTime: 377,
        },
        {
            ...p7sSkills["forbidden_fruit"],
            startTime: 380,
            endTime: 384,
        },
        {
            ...p7sSkills["inviolate_purgation"],
            startTime: 391,
            endTime: 395,
        },
        {
            ...p7sSkills["light_of_life"],
            startTime: 403,
            endTime: 429,
        },
        {
            ...p7sSkills["stymphalian_strike"],
            startTime: 404,
            endTime: 407,
        },
        {
            ...p7sSkills["aero_3"],
            startTime: 405,
            endTime: 406,
        },
        {
            ...p7sSkills["holy_3"],
            startTime: 405,
            endTime: 406,
        },
        {
            ...p7sSkills["tornado"],
            startTime: 408,
            endTime: 421,
        },
        {
            ...p7sSkills["glare_3"],
            startTime: 408,
            endTime: 421,
        },
        {
            ...p7sSkills["aero_3"],
            startTime: 420,
            endTime: 421,
        },
        {
            ...p7sSkills["holy_3"],
            startTime: 420,
            endTime: 421,
        },
        {
            ...p7sSkills["light_of_life"],
            startTime: 434,
            endTime: 460,
        },
        {
            ...p7sSkills["aero_3"],
            startTime: 435,
            endTime: 436,
        },
        {
            ...p7sSkills["holy_3"],
            startTime: 435,
            endTime: 436,
        },
        {
            ...p7sSkills["tornado"],
            startTime: 422,
            endTime: 436,
        },
        {
            ...p7sSkills["glare_3"],
            startTime: 422,
            endTime: 436,
        },
        {
            ...p7sSkills["aero_3"],
            startTime: 450,
            endTime: 451,
        },
        {
            ...p7sSkills["holy_3"],
            startTime: 450,
            endTime: 451,
        },
        {
            ...p7sSkills["tornado"],
            startTime: 438,
            endTime: 451,
        },
        {
            ...p7sSkills["glare_3"],
            startTime: 438,
            endTime: 451,
        },
        {
            ...p7sSkills["tornado"],
            startTime: 453,
            endTime: 466,
        },
        {
            ...p7sSkills["glare_3"],
            startTime: 453,
            endTime: 466,
        },
        {
            ...p7sSkills["forbidden_fruit"],
            startTime: 471,
            endTime: 475,
        },
        {
            ...p7sSkills["roots_of_attis"],
            startTime: 482,
            endTime: 485,
        },
        {
            ...p7sSkills["glare_cast"],
            startTime: 488,
            endTime: 493,
        },
        {
            ...p7sSkills["stymphalian_strike"],
            startTime: 497,
            endTime: 500,
        },
        {
            ...p7sSkills["glare_resolves"],
            startTime: 499,
            endTime: 503,
        },
        {
            ...p7sSkills["famines_harvest"],
            startTime: 503,
            endTime: 507,
        },
        {
            ...p7sSkills["forbidden_fruit"],
            startTime: 509,
            endTime: 512,
        },
        {
            ...p7sSkills["stymphalian_strike"],
            startTime: 525,
            endTime: 528,
        },
        {
            ...p7sSkills["bullish_swipe"],
            startTime: 525,
            endTime: 528,
        },
        {
            ...p7sSkills["bullish_slash"],
            startTime: 527,
            endTime: 528,
        },
        {
            ...p7sSkills["deaths_harvest"],
            startTime: 536,
            endTime: 540,
        },
        {
            ...p7sSkills["forbidden_fruit"],
            startTime: 542,
            endTime: 545,
        },
        {
            ...p7sSkills["static_path"],
            startTime: 558,
            endTime: 561,
        },
        {
            ...p7sSkills["static_moon"],
            startTime: 558,
            endTime: 561,
        },
        {
            ...p7sSkills["wars_harvest"],
            startTime: 569,
            endTime: 573,
        },
        {
            ...p7sSkills["forbidden_fruit"],
            startTime: 575,
            endTime: 578,
        },
        {
            ...p7sSkills["bullish_slash"],
            startTime: 592,
            endTime: 593,
        },
        {
            ...p7sSkills["bronze_bellows"],
            startTime: 592,
            endTime: 593,
        },
        {
            ...p7sSkills["static_path"],
            startTime: 592,
            endTime: 593,
        },
        {
            ...p7sSkills["spark_of_life"],
            startTime: 601,
            endTime: 606,
        },
        {
            ...p7sSkills["bough_of_attis_hit"],
            startTime: 620,
            endTime: 627,
        },
        {
            ...p7sSkills["holy_3"],
            startTime: 621,
            endTime: 627,
        },
        {
            ...p7sSkills["bough_of_attis_punch"],
            startTime: 629,
            endTime: 634,
        },
        {
            ...p7sSkills["spark_of_life"],
            startTime: 637,
            endTime: 642,
        },
        {
            ...p7sSkills["spark_of_life"],
            startTime: 651,
            endTime: 656,
        },
        {
            ...p7sSkills["light_of_life_enrage"],
            startTime: 663,
            endTime: 673,
        },
    ]