import { damageTypes, targets } from '../cooldowns/constants';

export const p8sp1v2Info =
{
    name: "Abyssos: The Eigth Circle (Savage) | Phase 1 | Snake First",
    abbreviation: "P8S P1 V2",
    boss: "Hephaistos",
    length: 472,
    level: 90
}

export const p8sp1v2Skills =
{
    genesis_of_flame: {
        id: "genesis_of_flame",
        name: "Genesis of Flame",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Raidwide",
    },
    conceptual_octa_tetra: {
        id: "conceptual_octa_tetra",
        name: "Conceptual Octaflare/Tetraflare (cast)",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Individual AoEs (octa) or partner stacks (tetra) stored for later",
    },
    volcanic_torches: {
        id: "volcanic_torches",
        name: "Volcanic Torches",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Blue flames spawn and begin moving",
    },
    torch_flame: {
        id: "torch_flame",
        name: "Torch Flame",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Squares outlined by Volcanic Torches explode",
    },
    sunforge: {
        id: "sunforge",
        name: "Sunforge",
        damageType: damageTypes.MAGIC,
        target: targets.DIRECTIONAL,
        avoidable: true,
        notes: "Spawns snake (cleaves middle) or phoenix (cleaves outsides)",
    },
    emergent_octa_tetra: {
        id: "emergent_octa_tetra",
        name: "Emergent Octaflare/Tetraflare",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Stored octa/tetraflare resolves",
    },
    flameviper_1: {
        id: "flameviper_1",
        name: "Flameviper 1",
        damageType: damageTypes.MAGIC,
        target: targets.MT,
        avoidable: false,
        tankbuster: true,
        notes: "Line cleave tankbuster applies vuln; swap required",
    },
    flameviper_2: {
        id: "flameviper_2",
        name: "Flameviper 2",
        damageType: damageTypes.MAGIC,
        target: targets.MT,
        avoidable: false,
        tankbuster: true,
        notes: "Untelegraphed second hit of buster; must swap back as autos will kill while vuln is up",
    },
    reforged_reflection: {
        id: "reforged_reflection",
        name: "Reforged Reflection",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: true,
        notes: "Transforms into dog or snake",
    },
    footprint: {
        id: "footprint",
        name: "Footprint",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: false,
        notes: "KB as boss drops back to ground after transforming",
    },
    rearing_rampage: {
        id: "rearing_rampage",
        name: "Rearing Rampage",
        damageType: damageTypes.PHYS,
        target: targets.PARTY,
        avoidable: false,
        notes: "Heavy-hitting raidwide; two players will be hit with uplifts and have Earth Res Down applied",
    },
    stomp_dead: {
        id: "stomp_dead",
        name: "Stomp Dead",
        damageType: damageTypes.PHYS,
        target: targets.PROXIMITY_FAR,
        avoidable: false,
        notes: "Hard-hitting jump on furthest player that must be taken in pairs; will kill if Earth Res Down hasn't fallen off",
    },
    illusory_creation_1: {
        id: "illusory_creation_1",
        name: "Illusory Creation",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Spawns four clones N/S/E/W",
    },
    creation_on_command: {
        id: "creation_on_command",
        name: "Creation on Command",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Clones begin using Sunforge in pairs",
    },
    manifold_flames: {
        id: "manifold_flames",
        name: "Manifold Flames",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Untelegraphed AoEs hit all DPS or all tanks/heals and applies vuln",
    },
    manifold_flames_protean: {
        id: "manifold_flames_protean",
        name: "Nest of Flamevipers",
        damageType: damageTypes.MAGIC,
        target: targets.PROXIMITY_CLOSE4,
        avoidable: false,
        notes: "Line cleaves on four closest players; must be taken by role that didn't get hit with AoEs",
    },
    clone_sunforge_1: {
        id: "clone_sunforge_1",
        name: "Sunforge",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "One clone spawns snake; one clone spawns phoenix",
    },
    clone_sunforge_2: {
        id: "clone_sunforge_2",
        name: "Sunforge",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Two clones both spawn snake or both spawn phoenix",
    },
    flameviper_tetraflare: {
        id: "flameviper_tetraflare",
        name: "Nest of Flamevipers/Tetraflare",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Line cleaves on all party members (Flamevipers) or partner stacks (Tetraflare)",
    },
    snaking_kick: {
        id: "snaking_kick",
        name: "Snaking Kick",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: true,
        notes: "AoE inside boss's hitbox",
    },
    gorgomanteia_1: {
        id: "gorgomanteia_1",
        name: "Gorgomanteia",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Eye/Blood of the Gorgon and First/Second in Line debuffs go out",
    },
    into_the_shadows_1: {
        id: "into_the_shadows_1",
        name: "Into the Shadows",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Spawns snakes in two sets of two",
    },
    petrification: {
        id: "petrification",
        name: "Petrification",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: true,
        notes: "Gaze attack from snakes when they emerge",
    },
    gorgoneion: {
        id: "gorgoneion",
        name: "Gorgoneion",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: true,
        notes: "Adds enrage if not petrified & killed",
    },
    eye: {
        id: "eye",
        name: "Eye of the Gorgon",
        damageType: damageTypes.NONE,
        target: targets.DIRECTIONAL,
        avoidable: true,
        notes: "Party members with Eye debuff shoot petrifying cone AoE in front of them as debuff expires",
    },
    blood: {
        id: "blood",
        name: "Blood of the Gorgon",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Individual AoE on party members with Blood debuff as debuff expires; kills petrified snakes",
    },
    ektothermos: {
        id: "ektothermos",
        name: "Ektothermos",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Heavy-hitting raidwide",
    },
    fourfold_fires: {
        id: "fourfold_fires",
        name: "Fourfold Fires",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Spawns four proximity AoEs from corners",
    },
    abyssal_fires: {
        id: "abyssal_fires",
        name: "Abyssal Fires",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: false,
        notes: "Proximity AoEs resolve and leave fire puddles",
    },
    cthonic_vent_cast: {
        id: "cthonic_vent_cast",
        name: "Cthonic Vent",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Spawns fire snakes in two puddles that begin bubbling more than the other two",
    },
    cthonic_vent_resolves: {
        id: "cthonic_vent_resolves",
        name: "Cthonic Vent (AoE)",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Large AoE around fire puddles as snakes emerge and move to new puddles",
    },
    octa_tetra: {
        id: "octa_tetra",
        name: "Octaflare/Tetraflare",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Individual AoEs (octa) or partner stacks (tetra); resolves at end of cast (not stored)",
    },
    quadrupedal_crush_impact: {
        id: "quadrupedal_crush_impact",
        name: "Quadrupedal Crush/Impact",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: true,
        notes: "Boss jumps to wall with either large AoE (Crush) or long KB (Impact) from landing spot",
    },
    blazing_footfalls: {
        id: "blazing_footfalls",
        name: "Blazing Footfalls",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Shows indicators of location/direction/order of subsequent dashes & jumps",
    },
    trailblaze: {
        id: "trailblaze",
        name: "Trailblaze",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: false,
        notes: "Boss dashes with KB from lines along middle murder zone",
    },
    into_the_shadows_2: {
        id: "into_the_shadows_2",
        name: "Into the Shadows",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Spawns four snakes at once",
    },
    gorgomanteia_2: {
        id: "gorgomanteia_2",
        name: "Gorgomanteia",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Eye/Blood/Crown/Breath of the Gorgon debuffs go out",
    },
    gorgospit_1: {
        id: "gorgospit_1",
        name: "Gorgospit",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Clones shoot line cleaves through outer tiles",
    },
    illusory_creation_2: {
        id: "illusory_creation_2",
        name: "Illusory Creation",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Spawns one clone on outside of arena",
    },
    gorgospit_2: {
        id: "gorgospit_2",
        name: "Gorgospit",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Clone shoots line cleave directly in front; kills any petrified snakes in its path",
    },
    crown: {
        id: "crown",
        name: "Crown of the Gorgon",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: true,
        notes: "Gaze attack from players with Crown debuff as it expires; must line of sight Crown players behind petrified snake",
    },
    breath: {
        id: "breath",
        name: "Breath of the Gorgon",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "4-man stacks on players with Breath debuff as it expires; kills petrified snakes",
    },
    genesis_of_flame_enrage: {
        id: "genesis_of_flame_enrage",
        name: "Genesis of Flamre",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
    },
    conceptual_di_tetra: {
        id: "conceptual_di_tetra",
        name: "Conceptual Diflare/Tetraflare",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "4-man stacks (diflare) or partner stacks (tetraflare) stored for later",
    },
    emergent_di_tetra: {
        id: "emergent_di_tetra",
        name: "Emergent Diflare/Tetraflare",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Stored di/tetraflare resolves",
    },
}

export const p8sp1v2Timeline =
[
    {
        ...p8sp1v2Skills["genesis_of_flame"],
        startTime: 7,
        endTime: 12,
    },
    {
        ...p8sp1v2Skills["conceptual_octa_tetra"],
        startTime: 15,
        endTime: 18,
    },
    {
        ...p8sp1v2Skills["volcanic_torches"],
        startTime: 21,
        endTime: 24,
    },
    {
        ...p8sp1v2Skills["torch_flame"],
        startTime: 37,
        endTime: 38,
    },
    {
        ...p8sp1v2Skills["sunforge"],
        startTime: 32,
        endTime: 40,
    },
    {
        ...p8sp1v2Skills["emergent_octa_tetra"],
        startTime: 40,
        endTime: 41,
    },
    {
        ...p8sp1v2Skills["flameviper_1"],
        startTime: 42,
        endTime: 48,
    },
    {
        ...p8sp1v2Skills["flameviper_2"],
        startTime: 50,
        endTime: 51,
    },
    {
        ...p8sp1v2Skills["reforged_reflection"],
        startTime: 60,
        endTime: 63,
    },
    {
        ...p8sp1v2Skills["snaking_kick"],
        startTime: 69,
        endTime: 70,
    },
    {
        ...p8sp1v2Skills["gorgomanteia_1"],
        startTime: 74,
        endTime: 77,
    },
    {
        ...p8sp1v2Skills["into_the_shadows_1"],
        startTime: 80,
        endTime: 83,
    },
    {
        ...p8sp1v2Skills["petrification"],
        startTime: 89,
        endTime: 97,
    },
    {
        ...p8sp1v2Skills["gorgoneion"],
        startTime: 100,
        endTime: 103,
    },
    {
        ...p8sp1v2Skills["eye"],
        startTime: 99,
        endTime: 100,
    },
    {
        ...p8sp1v2Skills["blood"],
        startTime: 102,
        endTime: 103,
    },
    {
        ...p8sp1v2Skills["petrification"],
        startTime: 104,
        endTime: 105,
    },
    {
        ...p8sp1v2Skills["gorgoneion"],
        startTime: 108,
        endTime: 111,
    },
    {
        ...p8sp1v2Skills["eye"],
        startTime: 107,
        endTime: 108,
    },
    {
        ...p8sp1v2Skills["blood"],
        startTime: 110,
        endTime: 111,
    },
    {
        ...p8sp1v2Skills["ektothermos"],
        startTime: 116,
        endTime: 121,
    },
    {
        ...p8sp1v2Skills["illusory_creation_1"],
        startTime: 136,
        endTime: 139,
    },
    {
        ...p8sp1v2Skills["creation_on_command"],
        startTime: 143,
        endTime: 146,
    },
    {
        ...p8sp1v2Skills["manifold_flames"],
        startTime: 146,
        endTime: 154,
    },
    {
        ...p8sp1v2Skills["clone_sunforge_1"],
        startTime: 149,
        endTime: 154,
    },
    {
        ...p8sp1v2Skills["manifold_flames_protean"],
        startTime: 157,
        endTime: 158,
    },
    {
        ...p8sp1v2Skills["flameviper_tetraflare"],
        startTime: 161,
        endTime: 166,
    },
    {
        ...p8sp1v2Skills["clone_sunforge_2"],
        startTime: 158,
        endTime: 166,
    },
    {
        ...p8sp1v2Skills["torch_flame"],
        startTime: 178,
        endTime: 179,
    },
    {
        ...p8sp1v2Skills["genesis_of_flame"],
        startTime: 178,
        endTime: 183,
    },
    {
        ...p8sp1v2Skills["reforged_reflection"],
        startTime: 193,
        endTime: 196,
    },
    {
        ...p8sp1v2Skills["footprint"],
        startTime: 201,
        endTime: 202,
    },
    {
        ...p8sp1v2Skills["rearing_rampage"],
        startTime: 203,
        endTime: 208,
    },
    {
        ...p8sp1v2Skills["rearing_rampage"],
        startTime: 209,
        endTime: 210,
    },
    {
        ...p8sp1v2Skills["rearing_rampage"],
        startTime: 211,
        endTime: 212,
    },
    {
        ...p8sp1v2Skills["rearing_rampage"],
        startTime: 213,
        endTime: 214,
    },
    {
        ...p8sp1v2Skills["stomp_dead"],
        startTime: 217,
        endTime: 222,
    },
    {
        ...p8sp1v2Skills["stomp_dead"],
        startTime: 223,
        endTime: 224,
    },
    {
        ...p8sp1v2Skills["stomp_dead"],
        startTime: 225,
        endTime: 226,
    },
    {
        ...p8sp1v2Skills["stomp_dead"],
        startTime: 227,
        endTime: 228,
    },
    {
        ...p8sp1v2Skills["conceptual_octa_tetra"],
        startTime: 243,
        endTime: 246,
    },
    {
        ...p8sp1v2Skills["fourfold_fires"],
        startTime: 249,
        endTime: 252,
    },
    {
        ...p8sp1v2Skills["abyssal_fires"],
        startTime: 253,
        endTime: 258,
    },
    {
        ...p8sp1v2Skills["cthonic_vent_cast"],
        startTime: 258,
        endTime: 261,
    },
    {
        ...p8sp1v2Skills["cthonic_vent_resolves"],
        startTime: 269,
        endTime: 270,
    },
    {
        ...p8sp1v2Skills["cthonic_vent_resolves"],
        startTime: 276,
        endTime: 277,
    },
    {
        ...p8sp1v2Skills["octa_tetra"],
        startTime: 272,
        endTime: 277,
    },
    {
        ...p8sp1v2Skills["cthonic_vent_resolves"],
        startTime: 284,
        endTime: 285,
    },
    {
        ...p8sp1v2Skills["sunforge"],
        startTime: 283,
        endTime: 291,
    },
    {
        ...p8sp1v2Skills["emergent_octa_tetra"],
        startTime: 290,
        endTime: 291,
    },
    {
        ...p8sp1v2Skills["flameviper_1"],
        startTime: 293,
        endTime: 358,
    },
    {
        ...p8sp1v2Skills["flameviper_2"],
        startTime: 300,
        endTime: 301,
    },
    {
        ...p8sp1v2Skills["reforged_reflection"],
        startTime: 311,
        endTime: 314,
    },
    {
        ...p8sp1v2Skills["snaking_kick"],
        startTime: 320,
        endTime: 321,
    },
    {
        ...p8sp1v2Skills["gorgomanteia_2"],
        startTime: 324,
        endTime: 327,
    },
    {
        ...p8sp1v2Skills["into_the_shadows_2"],
        startTime: 330,
        endTime: 333,
    },
    {
        ...p8sp1v2Skills["petrification"],
        startTime: 339,
        endTime: 347,
    },
    {
        ...p8sp1v2Skills["gorgospit_1"],
        startTime: 346,
        endTime: 347,
    },
    {
        ...p8sp1v2Skills["gorgoneion"],
        startTime: 351,
        endTime: 354,
    },
    {
        ...p8sp1v2Skills["eye"],
        startTime: 350,
        endTime: 351,
    },
    {
        ...p8sp1v2Skills["blood"],
        startTime: 350,
        endTime: 351,
    },
    {
        ...p8sp1v2Skills["illusory_creation_2"],
        startTime: 353,
        endTime: 356,
    },
    {
        ...p8sp1v2Skills["eye"],
        startTime: 356,
        endTime: 357,
    },
    {
        ...p8sp1v2Skills["blood"],
        startTime: 356,
        endTime: 357,
    },
    {
        ...p8sp1v2Skills["gorgospit_2"],
        startTime: 365,
        endTime: 366,
    },
    {
        ...p8sp1v2Skills["crown"],
        startTime: 365,
        endTime: 366,
    },
    {
        ...p8sp1v2Skills["breath"],
        startTime: 366,
        endTime: 367,
    },
    {
        ...p8sp1v2Skills["flameviper_1"],
        startTime: 375,
        endTime: 380,
    },
    {
        ...p8sp1v2Skills["flameviper_2"],
        startTime: 383,
        endTime: 384,
    },
    {
        ...p8sp1v2Skills["reforged_reflection"],
        startTime: 393,
        endTime: 396,
    },
    {
        ...p8sp1v2Skills["footprint"],
        startTime: 402,
        endTime: 403,
    },
    {
        ...p8sp1v2Skills["quadrupedal_crush_impact"],
        startTime: 404,
        endTime: 410,
    },
    {
        ...p8sp1v2Skills["conceptual_di_tetra"],
        startTime: 412,
        endTime: 415,
    },
    {
        ...p8sp1v2Skills["blazing_footfalls"],
        startTime: 418,
        endTime: 430,
    },
    {
        ...p8sp1v2Skills["trailblaze"],
        startTime: 430,
        endTime: 431,
    },
    {
        ...p8sp1v2Skills["emergent_di_tetra"],
        startTime: 431,
        endTime: 432,
    },
    {
        ...p8sp1v2Skills["quadrupedal_crush_impact"],
        startTime: 434,
        endTime: 435,
    },
    {
        ...p8sp1v2Skills["trailblaze"],
        startTime: 439,
        endTime: 440,
    },
    {
        ...p8sp1v2Skills["quadrupedal_crush_impact"],
        startTime: 441,
        endTime: 442,
    },
    {
        ...p8sp1v2Skills["torch_flame"],
        startTime: 445,
        endTime: 446,
    },
    {
        ...p8sp1v2Skills["genesis_of_flame"],
        startTime: 454,
        endTime: 459,
    },
    {
        ...p8sp1v2Skills["genesis_of_flame_enrage"],
        startTime: 467,
        endTime: 472,
    },
]