import { damageTypes, targets } from '../cooldowns/constants';

export const topInfo =
{
    name: "The Omega Protocol (Ultimate)",
    abbreviation: "TOP",
    boss: "Omega",
    length: 1143,
    level: 90
}

export const topSkills =
{
    program_loop: {
        id: "program_loop",
        name: "Program Loop",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        damage: 0,
    },
    blaster: {
        id: "blaster",
        name: "Blaster",
        damageType: damageTypes.MAGIC,
        target: targets.TETHER,
        avoidable: false,
        notes: "Tether AoE; applies Twice-Come Ruin and HP Penalty which drops max HP to 1% of its normal value",
        damage: 0,
    },
    storage_violation: {
        id: "storage_violation",
        name: "Storage Violation",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: false,
        notes: "Tower; cannot be soaked with HP Penalty",
        damage: 33000,
    },
    pantokrator: {
        id: "pantokrator",
        name: "Pantokrator",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Starts firing rotating flamethrower cones and periodically spawning AoEs under players",
        damage: 0,
    },
    guided_missile_kyrios: {
        id: "guided_missile_kyrios",
        name: "Guided Missile Kyrios",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "AoE damage upon Guided Missile Kyrios Incoming debuff expiring; applies Magic Vuln Up",
        damage: 63000,
    },
    condensed_wave_cannon_kyrios: {
        id: "condensed_wave_cannon_kyrios",
        name: "Condensed Wave Cannon Kyrios",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "3-man line stack on target upon Condensed Wave Cannon Kyrios debuff expiring; applies Magic Vuln Up",
        damage: 57000,
    },
    diffuse_wave_cannon_kyrios: {
        id: "diffuse_wave_cannon_kyrios",
        name: "Diffuse Wave Cannon Kyrios",
        damageType: damageTypes.MAGIC,
        target: targets.AGGRO_1_2,
        avoidable: false,
        tankbuster: true,
        notes: "5 consecutive cleaves applying Magic Vuln Up",
        damage: 60000,
    },
    wave_cannon_kyrios: {
        id: "wave_cannon_kyrios",
        name: "Wave Cannon Kyrios",
        damageType: damageTypes.MAGIC,
        target: targets.PROXIMITY_CLOSE3,
        avoidable: false,
        notes: "Line AoEs applying Magic Vuln Up",
        damage: 33000,
    },
    atomic_ray_enrage: {
        id: "atomic_ray_enrage",
        name: "Atomic Ray (Enrage)",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
        damage: 999999,
    },
    firewall: {
        id: "firewall",
        name: "Firewall",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        notes: "Applies Packet Filter M and Packet Filter F; players closest to M get Packet Filter F and vice versa",
        damage: 0,
    },
    solar_ray_p2: {
        id: "solar_ray_p2",
        name: "Solar Ray",
        damageType: damageTypes.MAGIC,
        target: targets.AGGRO_1_2,
        avoidable: false,
        tankbuster: true,
        notes: "AoE busters on top aggro for M and F",
        damage: 185000,
    },
    party_synergy: {
        id: "party_synergy",
        name: "Party Synergy",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Spawns clones & Playstation tethers",
        damage: 0,
    },
    efficient_bladework_beyond_strength: {
        id: "efficient_bladework_beyond_strength",
        name: "Efficient Bladework/Beyond Strength",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: true,
        notes: "Chariot (Efficient Bladework/sword) or dynamo (Beyond Strength/shield) from Omega-M",
        damage: 999999,
    },
    superliminal_steel_blizzard_3: {
        id: "superliminal_steel_blizzard_3",
        name: "Superliminal Steel/Optimized Blizzard III",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: true,
        notes: "Hot Wing (Superliminal Steel/sword) or cross through hitbox (Blizzard III/staff) from Omega-F",
        damage: 999999,
    },
    suppression: {
        id: "suppression",
        name: "Suppression",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Line AoE through middle of arena from eyeball",
        damage: 999999,
    },
    optimized_fire_3: {
        id: "optimized_fire_3",
        name: "Optimized Fire III",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Individual AoEs on all players; applies Magic Vuln Up",
        damage: 30000,
    },
    discharger: {
        id: "discharger",
        name: "Discharger",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "KB from Omega-F",
        damage: 0,
    },
    spotlight: {
        id: "spotlight",
        name: "Spotlight",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Two light party stack markers; applies Magic Vuln Up",
        damage: 53000,
    },
    efficient_bladework: {
        id: "efficient_bladework",
        name: "Efficient Bladework",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: true,
        notes: "Large chariot around Omega-M",
        damage: 999999,
    },
    synthetic_shield: {
        id: "synthetic_shield",
        name: "Synthetic Shield",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        notes: "Omega-M spawns a shield",
        damage: 0,
    },
    limitless_synergy: {
        id: "limitless_synergy",
        name: "Limitless Synergy",
        damageType: damageTypes.NONE,
        target: targets.ARENA,
        avoidable: false,
        damage: 0,
    },
    optimized_bladedance: {
        id: "optimized_bladedance",
        name: "Optimized Bladedance",
        damageType: damageTypes.PHYS,
        target: targets.TETHER,
        avoidable: false,
        tankbuster: true,
        notes: "Two massive cleave tether tankbusters",
        damage: 209000,
    },
    optimized_sagittarius_arrow: {
        id: "optimized_sagittarius_arrow",
        name: "Optimized Sagittarius Arrow",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: true,
        notes: "Line AoE through center of arena",
        damage: 999999,
    },
    beyond_defense: {
        id: "beyond_defense",
        name: "Beyond Defense",
        damageType: damageTypes.PHYS,
        target: targets.PARTY,
        avoidable: false,
        notes: "Omega-M rushes one player and applies Twice-Come Ruin",
        damage: 30000,
    },
    optimized_meteor: {
        id: "optimized_meteor",
        name: "Optimized Meteor",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Flares on three players",
        damage: 70000,
    },
    pile_pitch: {
        id: "pile_pitch",
        name: "Pile Pitch",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Stack damage on random player; applies Twice-Come Ruin",
        damage: 40000,
    },
    cosmo_memory: {
        id: "cosmo_memory",
        name: "Cosmo Memory",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Heavy raidwide",
        damage: 90000,
    },
    laser_shower_enrage: {
        id: "laser_shower_enrage",
        name: "Laser Shower (Enrage)",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
        damage: 999999,
    },
    wave_repeater: {
        id: "wave_repeater",
        name: "Wave Repeater",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Concentric ground AoEs",
        damage: 999999,
    },
    sniper_cannon: {
        id: "sniper_cannon",
        name: "Sniper Cannon",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Solo AoEs on targeted players",
        damage: 70000,
    },
    high_powered_sniper_cannon: {
        id: "high_powered_sniper_cannon",
        name: "High-Powered Sniper Cannon",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "2-person stack AoEs",
        damage: 75000,
    },
    colossal_blow: {
        id: "colossal_blow",
        name: "Colossal Blow",
        damageType: damageTypes.PHYS,
        target: targets.ARENA,
        avoidable: true,
        notes: "Fist chariots",
        damage: 999999,
    },
    hello_world: {
        id: "hello_world",
        name: "Hello World",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        damage: 75000,
    },
    latent_defect: {
        id: "latent_defect",
        name: "Latent Defect",
        damageType: damageTypes.NONE,
        target: targets.PARTY,
        avoidable: false,
        damage: 0,
    },
    sync_bug: {
        id: "sync_bug",
        name: "Critical Synchronization Bug",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Stack debuff expires",
        damage: 40000,
    },
    overflow_bug: {
        id: "overflow_bug",
        name: "Critical Overflow Bug",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Defamation debuff expires",
        damage: 40000,
    },
    patch: {
        id: "patch",
        name: "Patch",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Close/far tethers must be broken before debuff expires; applies Magic Vuln Up and Twice-Come Ruin",
        damage: 22000,
    },
    critical_error: {
        id: "critical_error",
        name: "Critical Error",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        damage: 90000,
    },
    oversampled_wave_cannon: {
        id: "oversampled_wave_cannon",
        name: "Oversampled Wave Cannon",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        damage: 48000,
    },
    ion_efflux_enrage: {
        id: "ion_efflux_enrage",
        name: "Ion Efflux (Enrage)",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
        damage: 999999,
    },
    wave_cannon_solo: {
        id: "wave_cannon_solo",
        name: "Wave Cannon (Solo)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        damage: 35000,
    },
    wave_cannon_stack: {
        id: "wave_cannon_stack",
        name: "Wave Cannon (Stack)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        damage: 55000,
    },
    blue_screen_enrage: {
        id: "blue_screen_enrage",
        name: "Blue Screen (Enrage)",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
        damage: 999999,
    },
    solar_ray_p5: {
        id: "solar_ray_p5",
        name: "Solar Ray",
        damageType: damageTypes.MAGIC,
        target: targets.MT,
        avoidable: false,
        tankbuster: true,
        notes: "Applies Magic Vuln Up; requires swap",
        damage: 280000,
    },
    run_dynamis_delta: {
        id: "run_dynamis_delta",
        name: "Run: ****mi* (Delta Version)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        damage: 135000,
    },
    optical_laser: {
        id: "optical_laser",
        name: "Optical Laser",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
    },
    hello_distant_world: {
        id: "hello_distant_world",
        name: "Hello Distant World",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        damage: 48000,
    },
    hello_near_world: {
        id: "hello_near_world",
        name: "Hello Near World",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        damage: 48000,
    },
    run_dynamis_sigma: {
        id: "run_dynamis_sigma",
        name: "Run: ****mi* (Sigma Version)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        damage: 135000,
    },
    run_dynamis_omega: {
        id: "run_dynamis_omega",
        name: "Run: ****mi* (Omega Version)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        damage: 135000,
    },
    blind_faith: {
        id: "blind_faith",
        name: "Blind Faith (Enrage)",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
        damage: 72000,
    },
    flash_gale: {
        id: "flash_gale",
        name: "Flash Gale",
        damageType: damageTypes.MAGIC,
        target: targets.AGGRO_1_2,
        avoidable: false,
        notes: "AoE autos",
        damage: 33000,
    },
    cosmo_dive_party: {
        id: "cosmo_dive_party",
        name: "Cosmo Dive (Party)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Non-tanks stack",
        damage: 95000,
    },
    unlimited_wave_cannon: {
        id: "unlimited_wave_cannon",
        name: "Unlimited Wave Cannon",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Exaflares begin",
    },
    cosmo_arrow: {
        id: "cosmo_arrow",
        name: "Cosmo Arrow",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Repeated ground AoEs ever ~2 seconds",
        damage: 999999,
    },
    wave_cannon_wc_tanks: {
        id: "wave_cannon_wc_tanks",
        name: "Wave Cannon (Wild Charge, Tanks)",
        damageType: damageTypes.MAGIC,
        target: targets.AGGRO_1_2,
        avoidable: false,
        tankbuster: true,
        notes: "Tanks in front of party for line stack",
        damage: 335000,
    },
    cosmo_meteor_cast: {
        id: "cosmo_meteor_cast",
        name: "Cosmo Meteor (Cast)",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Large baited AoEs in middle",
        damage: 999999,
    },
    magic_number: {
        id: "magic_number",
        name: "Magic Number",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Tank LB3 required to survive initial hit; healer LB3 required to remove Magic Number debuff",
        damage: 290000,
    },
    run_dynamis_enrage: {
        id: "run_dynamis_enrage",
        name: "Run: ****mi* (Enrage)",
        damageType: damageTypes.ENRAGE,
        target: targets.PARTY,
        avoidable: false,
        damage: 999999,
    },
    hyper_pulse: {
        id: "hyper_pulse",
        name: "Hyper Pulse",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        damage: 68000,
    },
    patch_instant: {
        id: "patch_instant",
        name: "Patch (Instant)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Instant Christmas tether break (if stacking both tethers between stack towers for last towers)",
        damage: 22000,
    },
    diffuse_wave_cannon: {
        id: "diffuse_wave_cannon",
        name: "Diffuse Wave Cannon",
        damageType: damageTypes.MAGIC,
        target: targets.ARENA,
        avoidable: true,
        notes: "Large cleaves to Final Omega's front/back or left/right",
        damage: 999999,
    },
    cosmo_memory_p6: {
        id: "cosmo_memory_p6",
        name: "Cosmo Memory",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Tank LB3 required",
        damage: 360000,
    },
    cosmo_dive_tanks: {
        id: "cosmo_dive_tanks",
        name: "Cosmo Dive (Tanks)",
        damageType: damageTypes.MAGIC,
        target: targets.AGGRO_1_2,
        avoidable: false,
        tankbuster: true,
        notes: "AoE tankbuster",
        damage: 255000,
    },
    wave_cannon_solo_p6: {
        id: "wave_cannon_solo_p6",
        name: "Wave Cannon (Solo)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        damage: 86000,
    },
    wave_cannon_wc_party: {
        id: "wave_cannon_wc_party",
        name: "Wave Cannon (Wild Charge, Party)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Line stack behind tanks",
        damage: 110000,
    },
    cosmo_meteor_aoes: {
        id: "cosmo_meteor_aoes",
        name: "Cosmo Meteor (AoEs)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Two sets of four AoEs on random players",
        damage: 95000,
    },
    cosmo_meteor_flares: {
        id: "cosmo_meteor_flares",
        name: "Cosmo Meteor (Flares)",
        damageType: damageTypes.MAGIC,
        target: targets.PARTY,
        avoidable: false,
        notes: "Three players targeted for flares",
        damage: 90000,
    },
}

export const topTimeline =
[
    {
        ...topSkills["program_loop"],
        startTime: 10,
        endTime: 15,
    },
    {
        ...topSkills["blaster"],
        startTime: 21,
        endTime: 29,
    },
    {
        ...topSkills["storage_violation"],
        startTime: 28,
        endTime: 29,
    },
    {
        ...topSkills["blaster"],
        startTime: 30,
        endTime: 38,
    },
    {
        ...topSkills["storage_violation"],
        startTime: 37,
        endTime: 38,
    },
    {
        ...topSkills["blaster"],
        startTime: 39,
        endTime: 47,
    },
    {
        ...topSkills["storage_violation"],
        startTime: 46,
        endTime: 47,
    },
    {
        ...topSkills["blaster"],
        startTime: 48,
        endTime: 56,
    },
    {
        ...topSkills["storage_violation"],
        startTime: 55,
        endTime: 56,
    },
    {
        ...topSkills["pantokrator"],
        startTime: 64,
        endTime: 69,
    },
    {
        ...topSkills["guided_missile_kyrios"],
        startTime: 80,
        endTime: 81,
    },
    {
        ...topSkills["guided_missile_kyrios"],
        startTime: 86,
        endTime: 87,
    },
    {
        ...topSkills["guided_missile_kyrios"],
        startTime: 92,
        endTime: 93,
    },
    {
        ...topSkills["guided_missile_kyrios"],
        startTime: 98,
        endTime: 99,
    },
    {
        ...topSkills["condensed_wave_cannon_kyrios"],
        startTime: 80,
        endTime: 81,
    },
    {
        ...topSkills["condensed_wave_cannon_kyrios"],
        startTime: 86,
        endTime: 87,
    },
    {
        ...topSkills["condensed_wave_cannon_kyrios"],
        startTime: 92,
        endTime: 93,
    },
    {
        ...topSkills["condensed_wave_cannon_kyrios"],
        startTime: 98,
        endTime: 99,
    },
    {
        ...topSkills["wave_cannon_kyrios"],
        startTime: 103,
        endTime: 108,
    },
    {
        ...topSkills["wave_cannon_kyrios"],
        startTime: 112,
        endTime: 117,
    },
    {
        ...topSkills["diffuse_wave_cannon_kyrios"],
        startTime: 108,
        endTime: 116,
    },
    {
        ...topSkills["atomic_ray_enrage"],
        startTime: 123,
        endTime: 128,
    },
    {
        ...topSkills["firewall"],
        startTime: 130,
        endTime: 132,
    },
    {
        ...topSkills["solar_ray_p2"],
        startTime: 137,
        endTime: 142,
    },
    {
        ...topSkills["party_synergy"],
        startTime: 157,
        endTime: 160,
    },
    {
        ...topSkills["efficient_bladework_beyond_strength"],
        startTime: 168,
        endTime: 170,
    },
    {
        ...topSkills["superliminal_steel_blizzard_3"],
        startTime: 168,
        endTime: 170,
    },
    {
        ...topSkills["suppression"],
        startTime: 175,
        endTime: 176,
    },
    {
        ...topSkills["optimized_fire_3"],
        startTime: 175,
        endTime: 176,
    },
    {
        ...topSkills["discharger"],
        startTime: 181,
        endTime: 182,
    },
    {
        ...topSkills["spotlight"],
        startTime: 186,
        endTime: 187,
    },
    {
        ...topSkills["efficient_bladework"],
        startTime: 186,
        endTime: 187,
    },
    {
        ...topSkills["synthetic_shield"],
        startTime: 199,
        endTime: 200,
    },
    {
        ...topSkills["limitless_synergy"],
        startTime: 205,
        endTime: 210,
    },
    {
        ...topSkills["optimized_bladedance"],
        startTime: 216,
        endTime: 224,
    },
    {
        ...topSkills["optimized_sagittarius_arrow"],
        startTime: 216,
        endTime: 225,
    },
    {
        ...topSkills["laser_shower_enrage"],
        startTime: 216,
        endTime: 273,
    },
    {
        ...topSkills["optimized_meteor"],
        startTime: 230,
        endTime: 238,
    },
    {
        ...topSkills["beyond_defense"],
        startTime: 230,
        endTime: 235,
    },
    {
        ...topSkills["cosmo_memory"],
        startTime: 242,
        endTime: 248,
    },
    {
        ...topSkills["pile_pitch"],
        startTime: 237,
        endTime: 238,
    },
    {
        ...topSkills["colossal_blow"],
        startTime: 299,
        endTime: 300,
    },
    {
        ...topSkills["colossal_blow"],
        startTime: 303,
        endTime: 304,
    },
    {
        ...topSkills["sniper_cannon"],
        startTime: 303,
        endTime: 304,
    },
    {
        ...topSkills["high_powered_sniper_cannon"],
        startTime: 303,
        endTime: 304,
    },
    {
        ...topSkills["hello_world"],
        startTime: 312,
        endTime: 317,
    },
    {
        ...topSkills["latent_defect"],
        startTime: 331,
        endTime: 341,
    },
    {
        ...topSkills["sync_bug"],
        startTime: 340,
        endTime: 341,
    },
    {
        ...topSkills["overflow_bug"],
        startTime: 340,
        endTime: 341,
    },
    {
        ...topSkills["patch"],
        startTime: 341,
        endTime: 344,
    },
    {
        ...topSkills["patch"],
        startTime: 341,
        endTime: 346,
    },
    {
        ...topSkills["latent_defect"],
        startTime: 352,
        endTime: 362,
    },
    {
        ...topSkills["sync_bug"],
        startTime: 361,
        endTime: 362,
    },
    {
        ...topSkills["overflow_bug"],
        startTime: 361,
        endTime: 362,
    },
    {
        ...topSkills["patch"],
        startTime: 362,
        endTime: 364,
    },
    {
        ...topSkills["patch"],
        startTime: 362,
        endTime: 367,
    },
    {
        ...topSkills["latent_defect"],
        startTime: 373,
        endTime: 383,
    },
    {
        ...topSkills["sync_bug"],
        startTime: 382,
        endTime: 383,
    },
    {
        ...topSkills["overflow_bug"],
        startTime: 382,
        endTime: 383,
    },
    {
        ...topSkills["patch"],
        startTime: 383,
        endTime: 386,
    },
    {
        ...topSkills["patch"],
        startTime: 383,
        endTime: 389,
    },
    {
        ...topSkills["patch_instant"],
        startTime: 403,
        endTime: 404,
    },
    {
        ...topSkills["latent_defect"],
        startTime: 395,
        endTime: 405,
    },
    {
        ...topSkills["sync_bug"],
        startTime: 404,
        endTime: 405,
    },
    {
        ...topSkills["overflow_bug"],
        startTime: 404,
        endTime: 405,
    },
    {
        ...topSkills["patch"],
        startTime: 405,
        endTime: 408,
    },
    {
        ...topSkills["critical_error"],
        startTime: 418,
        endTime: 426,
    },
    {
        ...topSkills["oversampled_wave_cannon"],
        startTime: 437,
        endTime: 447,
    },
    {
        ...topSkills["ion_efflux_enrage"],
        startTime: 453,
        endTime: 463,
    },
    {
        ...topSkills["wave_cannon_solo"],
        startTime: 479,
        endTime: 484,
    },
    {
        ...topSkills["wave_cannon_stack"],
        startTime: 488,
        endTime: 489,
    },
    {
        ...topSkills["wave_cannon_solo"],
        startTime: 493,
        endTime: 494,
    },
    {
        ...topSkills["wave_cannon_stack"],
        startTime: 498,
        endTime: 499,
    },
    {
        ...topSkills["wave_cannon_solo"],
        startTime: 503,
        endTime: 504,
    },
    {
        ...topSkills["wave_cannon_stack"],
        startTime: 508,
        endTime: 509,
    },
    {
        ...topSkills["blue_screen_enrage"],
        startTime: 517,
        endTime: 525,
    },
    {
        ...topSkills["solar_ray_p5"],
        startTime: 543,
        endTime: 549,
    },
    {
        ...topSkills["solar_ray_p5"],
        startTime: 551,
        endTime: 552,
    },
    {
        ...topSkills["run_dynamis_delta"],
        startTime: 560,
        endTime: 565,
    },
    {
        ...topSkills["patch"],
        startTime: 585,
        endTime: 586,
    },
    {
        ...topSkills["patch"],
        startTime: 585,
        endTime: 590,
    },
    {
        ...topSkills["beyond_defense"],
        startTime: 593,
        endTime: 594,
    },
    {
        ...topSkills["pile_pitch"],
        startTime: 598,
        endTime: 599,
    },
    {
        ...topSkills["oversampled_wave_cannon"],
        startTime: 598,
        endTime: 599,
    },
    {
        ...topSkills["patch"],
        startTime: 600,
        endTime: 608,
    },
    {
        ...topSkills["hello_near_world"],
        startTime: 611,
        endTime: 612,
    },
    {
        ...topSkills["hello_near_world"],
        startTime: 612,
        endTime: 613,
    },
    {
        ...topSkills["hello_near_world"],
        startTime: 613,
        endTime: 614,
    },
    {
        ...topSkills["hello_distant_world"],
        startTime: 611,
        endTime: 612,
    },
    {
        ...topSkills["hello_distant_world"],
        startTime: 612,
        endTime: 613,
    },
    {
        ...topSkills["hello_distant_world"],
        startTime: 613,
        endTime: 614,
    },
    {
        ...topSkills["patch"],
        startTime: 615,
        endTime: 620,
    },
    {
        ...topSkills["solar_ray_p5"],
        startTime: 625,
        endTime: 631,
    },
    {
        ...topSkills["solar_ray_p5"],
        startTime: 633,
        endTime: 634,
    },
    {
        ...topSkills["run_dynamis_sigma"],
        startTime: 642,
        endTime: 647,
    },
    {
        ...topSkills["hyper_pulse"],
        startTime: 668,
        endTime: 669,
    },
    {
        ...topSkills["wave_cannon_solo"],
        startTime: 668,
        endTime: 669,
    },
    {
        ...topSkills["discharger"],
        startTime: 677,
        endTime: 678,
    },
    {
        ...topSkills["storage_violation"],
        startTime: 681,
        endTime: 682,
    },
    {
        ...topSkills["superliminal_steel_blizzard_3"],
        startTime: 698,
        endTime: 699,
    },
    {
        ...topSkills["hyper_pulse"],
        startTime: 705,
        endTime: 706,
    },
    {
        ...topSkills["hello_near_world"],
        startTime: 705,
        endTime: 706,
    },
    {
        ...topSkills["hello_near_world"],
        startTime: 706,
        endTime: 707,
    },
    {
        ...topSkills["hello_near_world"],
        startTime: 707,
        endTime: 708,
    },
    {
        ...topSkills["hello_distant_world"],
        startTime: 705,
        endTime: 706,
    },
    {
        ...topSkills["hello_distant_world"],
        startTime: 706,
        endTime: 707,
    },
    {
        ...topSkills["hello_distant_world"],
        startTime: 707,
        endTime: 708,
    },
    {
        ...topSkills["solar_ray_p5"],
        startTime: 714,
        endTime: 720,
    },
    {
        ...topSkills["solar_ray_p5"],
        startTime: 722,
        endTime: 723,
    },
    {
        ...topSkills["run_dynamis_omega"],
        startTime: 732,
        endTime: 737,
    },
    {
        ...topSkills["superliminal_steel_blizzard_3"],
        startTime: 754,
        endTime: 755,
    },
    {
        ...topSkills["efficient_bladework_beyond_strength"],
        startTime: 754,
        endTime: 755,
    },
    {
        ...topSkills["diffuse_wave_cannon"],
        startTime: 754,
        endTime: 755,
    },
    {
        ...topSkills["superliminal_steel_blizzard_3"],
        startTime: 758,
        endTime: 759,
    },
    {
        ...topSkills["efficient_bladework_beyond_strength"],
        startTime: 758,
        endTime: 759,
    },
    {
        ...topSkills["diffuse_wave_cannon"],
        startTime: 758,
        endTime: 759,
    },
    {
        ...topSkills["hello_near_world"],
        startTime: 771,
        endTime: 772,
    },
    {
        ...topSkills["hello_near_world"],
        startTime: 772,
        endTime: 773,
    },
    {
        ...topSkills["hello_near_world"],
        startTime: 773,
        endTime: 774,
    },
    {
        ...topSkills["hello_distant_world"],
        startTime: 771,
        endTime: 772,
    },
    {
        ...topSkills["hello_distant_world"],
        startTime: 772,
        endTime: 773,
    },
    {
        ...topSkills["hello_distant_world"],
        startTime: 773,
        endTime: 774,
    },
    {
        ...topSkills["oversampled_wave_cannon"],
        startTime: 771,
        endTime: 772,
    },
    {
        ...topSkills["blaster"],
        startTime: 787,
        endTime: 788,
    },
    {
        ...topSkills["hello_near_world"],
        startTime: 789,
        endTime: 790,
    },
    {
        ...topSkills["hello_near_world"],
        startTime: 790,
        endTime: 791,
    },
    {
        ...topSkills["hello_near_world"],
        startTime: 791,
        endTime: 792,
    },
    {
        ...topSkills["hello_distant_world"],
        startTime: 789,
        endTime: 790,
    },
    {
        ...topSkills["hello_distant_world"],
        startTime: 790,
        endTime: 791,
    },
    {
        ...topSkills["hello_distant_world"],
        startTime: 791,
        endTime: 792,
    },
    {
        ...topSkills["solar_ray_p5"],
        startTime: 798,
        endTime: 804,
    },
    {
        ...topSkills["solar_ray_p5"],
        startTime: 805,
        endTime: 806,
    },
    {
        ...topSkills["blind_faith"],
        startTime: 815,
        endTime: 826,
    },
    {
        ...topSkills["cosmo_memory_p6"],
        startTime: 890,
        endTime: 896,
    },
    {
        ...topSkills["flash_gale"],
        startTime: 899,
        endTime: 900,
    },
    {
        ...topSkills["flash_gale"],
        startTime: 902,
        endTime: 903,
    },
    {
        ...topSkills["cosmo_arrow"],
        startTime: 903,
        endTime: 909,
    },
    {
        ...topSkills["cosmo_dive_tanks"],
        startTime: 918,
        endTime: 926,
    },
    {
        ...topSkills["cosmo_dive_party"],
        startTime: 918,
        endTime: 926,
    },
    {
        ...topSkills["flash_gale"],
        startTime: 933,
        endTime: 934,
    },
    {
        ...topSkills["flash_gale"],
        startTime: 936,
        endTime: 937,
    },
    {
        ...topSkills["unlimited_wave_cannon"],
        startTime: 937,
        endTime: 943,
    },
    {
        ...topSkills["wave_cannon_solo_p6"],
        startTime: 962,
        endTime: 963,
    },
    {
        ...topSkills["wave_cannon_solo_p6"],
        startTime: 964,
        endTime: 965,
    },
    {
        ...topSkills["wave_cannon_wc_tanks"],
        startTime: 971,
        endTime: 972,
    },
    {
        ...topSkills["wave_cannon_wc_party"],
        startTime: 971,
        endTime: 972,
    },
    {
        ...topSkills["flash_gale"],
        startTime: 976,
        endTime: 977,
    },
    {
        ...topSkills["flash_gale"],
        startTime: 979,
        endTime: 980,
    },
    {
        ...topSkills["cosmo_arrow"],
        startTime: 980,
        endTime: 986,
    },
    {
        ...topSkills["wave_cannon_solo_p6"],
        startTime: 996,
        endTime: 997,
    },
    {
        ...topSkills["wave_cannon_solo_p6"],
        startTime: 998,
        endTime: 999,
    },
    {
        ...topSkills["wave_cannon_wc_tanks"],
        startTime: 1005,
        endTime: 1006,
    },
    {
        ...topSkills["wave_cannon_wc_party"],
        startTime: 1005,
        endTime: 1006,
    },
    {
        ...topSkills["flash_gale"],
        startTime: 1010,
        endTime: 1011,
    },
    {
        ...topSkills["flash_gale"],
        startTime: 1013,
        endTime: 1014,
    },
    {
        ...topSkills["unlimited_wave_cannon"],
        startTime: 1014,
        endTime: 1020,
    },
    {
        ...topSkills["cosmo_dive_tanks"],
        startTime: 1034,
        endTime: 1040,
    },
    {
        ...topSkills["cosmo_dive_party"],
        startTime: 1034,
        endTime: 1040,
    },
    {
        ...topSkills["flash_gale"],
        startTime: 1047,
        endTime: 1048,
    },
    {
        ...topSkills["flash_gale"],
        startTime: 1050,
        endTime: 1051,
    },
    {
        ...topSkills["cosmo_meteor_cast"],
        startTime: 1056,
        endTime: 1062,
    },
    {
        ...topSkills["cosmo_meteor_aoes"],
        startTime: 1064,
        endTime: 1065,
    },
    {
        ...topSkills["cosmo_meteor_aoes"],
        startTime: 1065,
        endTime: 1066,
    },
    {
        ...topSkills["cosmo_meteor_aoes"],
        startTime: 1070,
        endTime: 1071,
    },
    {
        ...topSkills["cosmo_meteor_aoes"],
        startTime: 1071,
        endTime: 1072,
    },
    {
        ...topSkills["cosmo_meteor_flares"],
        startTime: 1075,
        endTime: 1083,
    },
    {
        ...topSkills["magic_number"],
        startTime: 1091,
        endTime: 1096,
    },
    {
        ...topSkills["magic_number"],
        startTime: 1108,
        endTime: 1113,
    },
    {
        ...topSkills["run_dynamis_enrage"],
        startTime: 1123,
        endTime: 1143,
    },
]